// Generated by `cargo xtask gen-ts` from the eo-api command manifest.
// Do not edit; regenerate after changing the Rust DTOs or manifest.
// CI holds this file in lock-step (`cargo xtask gen-ts --check`).

import { invokeCommand } from './invoke';

/** The serialised error every command rejects with. */
export type ApiErrorPayload = {
		message: string;
		kind: 'badRequest';
	} | {
		message: string;
		kind: 'notFound';
	} | {
		message: string;
		kind: 'conflict';
	} | {
		kind: 'internal';
	} | {
		kind: 'unavailable';
	};

/** The closed `kind` vocabulary of the error contract. */
export type ApiErrorKind = 'badRequest' | 'notFound' | 'conflict' | 'internal' | 'unavailable';

/** The error kinds as a runtime list, for guarding a raw rejection. */
export const API_ERROR_KINDS: readonly ApiErrorKind[] = ['badRequest', 'notFound', 'conflict', 'internal', 'unavailable'];

/**
 * The absorber component of a stored weapon setup.
 */
export interface AbsorberComponent {
	catalogId: string | null;
	name: string;
	decay: number;
	ammoBurn: number;
	absorptionPercent: number;
	markupPercent: number;
	isLimited: boolean;
}

/**
 * The accept verb's result: `{ok, skills_persisted}` on success, the
 * lone `error` on a refusal (each key skipped when absent, preserving
 * the HTTP polymorphic body exactly).
 */
export interface AcceptResult {
	ok?: boolean | null;
	skills_persisted?: number | null;
	error?: string | null;
}

/**
 * One thing an activity did to its stock: a listing across its whole
 * lifecycle, or a conversion into another item.
 * 
 * A listing appears once however far it has got. Creating and selling are the
 * same listing at two moments, not two entries.
 */
export interface ActivityHistoryEntry {
	id: string;
	/** `listing` or `conversion`. */
	kind: string;
	/** `pending`, `sold` or `expired` for a listing; `converted` otherwise. */
	status: string;
	itemName: string;
	/** What a conversion produced; `null` for a listing. */
	targetItem: string | null;
	/** When a listing resolved, or when it was listed if it has not; when a conversion happened. */
	occurredAt: string;
	quantity: number;
	ttValue: number;
	/** Sold listings only: the gain after both fees, and the part of it an activity may claim. */
	netMarkup: number | null;
	activityNetMarkup: number | null;
	/** Whether the sale can be taken back, leaving the listing open. */
	canRevertSale: boolean;
	/** Whether the entry can be undone outright, returning any stock it took. */
	canDelete: boolean;
	/** Why not, when it cannot, in terms a reader can act on. */
	undoBlockedReason: string | null;
	/** Already undone. Every effect it had is reversed and the entry is kept as the read-only record of a correction. */
	undone: boolean;
}

/**
 * The activity-recommender query. `professions` carries the target
 * profession name(s) for a `profession` target (one name, or several
 * for a family) and is ignored for `hp`.
 */
export interface ActivityRecommenderQuery {
	target: RecommenderTargetKind;
	professions?: string[];
}

/**
 * GET activity-recommender: candidates ranked by PES-to-+1 on the
 * target, plus the direct-grind reference for single-profession
 * targets. `error` is present only on the soft-error path (an unknown
 * profession name), matching the family's inline-render convention.
 */
export interface ActivityRecommenderResult {
	error?: string | null;
	pesCap: number;
	sampleStep: number;
	direct: RecommenderActivity | null;
	candidates: RecommenderActivity[];
}

/**
 * An undo payload: the history entry to take back.
 */
export interface ActivityUndoInput {
	id: string;
}

/**
 * The Tree Cutting aggregate: the tier-first comparison table.
 */
export interface AnalyticsHarvest {
	tierComparisons: HarvestTierComparison[];
}

/**
 * The Hunting aggregate: the per-mob and per-session-name comparison
 * tables (the observed and designated axes).
 */
export interface AnalyticsHunting {
	mobComparisons: MobComparison[];
	nameComparisons: NameComparison[];
}

/**
 * The Overview aggregate: the total return rate and trend, the returns /
 * losses breakdowns, the totals, and the day / month timelines.
 */
export interface AnalyticsOverview {
	totalReturnRate: number;
	trend: Trend;
	returnsBreakdown: ReturnsBreakdown;
	lossesBreakdown: LossesBreakdown;
	totalGains: number;
	totalLosses: number;
	timeline: TimelineDay[];
	monthlyBreakdown: MonthlyEntry[];
}

/**
 * The full assembled settings response. Field order is the wire order
 * the frontend contract expects (and the HTTP body carried).
 */
export interface AppSettings {
	gameConnection: GameConnection;
	hotbarHooksEnabled: boolean;
	repairOcrEnabled: boolean;
	endOfSessionArmourReminderEnabled: boolean;
	developerModeEnabled: boolean;
	/** The session facets the next session snapshots: the designated name (empty: not declared) and the skill boost (null: not declared; 0: declared deliberately unboosted). */
	sessionName: string;
	declaredSkillBoostPercent?: number | null;
	/** The slot-to-equipment map, carried through in its stored insertion order (`serde_json`'s `preserve_order`), so slot "0" stays last. */
	hotbar: Record<string, unknown>;
	trifecta: TrifectaSettings;
	harvestGuardrail: HarvestGuardrailSettings;
	lootFilterBlacklist: string[];
	dbPath: string;
	appVersion: string;
}

/**
 * The armour-cost result (echoes the submitted value, not the new total).
 */
export interface ArmourCostResult {
	sessionId: string;
	armourCost: number;
}

/**
 * A sale-confirmation payload: the price the auction actually fetched and
 * the additional fee charged at the point of sale.
 */
export interface AuctionConfirmInput {
	listingId: string;
	finalPrice: number;
	saleFee: number;
	resolvedAt?: string | null;
}

/**
 * An expiry payload: the listing came back unsold.
 */
export interface AuctionExpireInput {
	listingId: string;
	resolvedAt?: string | null;
}

/**
 * One auction listing across its lifecycle. Realised figures are `null`
 * until the listing is confirmed sold: an open auction has no price yet,
 * and an expired one never realised anything.
 */
export interface AuctionListing {
	id: string;
	itemName: string;
	quantity: number;
	attributedQty: number;
	unattributedQty: number;
	ttValue: number;
	attributedTt: number;
	startingBid: number;
	buyout: number | null;
	listingFee: number;
	listedAt: string;
	status: string;
	finalPrice: number | null;
	saleFee: number | null;
	resolvedAt: string | null;
	/** Net markup the activity may claim, after both auction fees and after removing the share covered by untracked stock. */
	activityNetMarkup: number | null;
	/** Sale proceeds above the listing's TT, before fees. */
	grossMarkup: number | null;
}

/**
 * An auction-listing creation payload. Dates are optional and default to
 * today; the fee is what the game quoted at listing time.
 */
export interface AuctionListingInput {
	itemName: string;
	quantity: number;
	startingBid: number;
	buyout?: number | null;
	listingFee: number;
	listedAt?: string | null;
}

/**
 * GET calibration: whether skills are calibrated and how fresh.
 */
export interface CalibrationStatus {
	calibrated: boolean;
	lastCalibration: string | null;
	stale: boolean;
}

/**
 * A capture verb's result: the status the grab settled on, plus the
 * 1-indexed page and whether the frame was captured. On a refusal the
 * page/captured extras are absent (the status carries the error).
 */
export interface CaptureResult {
	active: boolean;
	processing: boolean;
	captured_pages: number;
	expected_pages: number;
	last_scan_time: number | null;
	skills_count: number;
	configured: boolean;
	game_window_present: boolean;
	phase: ScanPhase;
	processing_progress: ScanProgress;
	has_pending_result: boolean;
	error: string | null;
	page?: number | null;
	captured?: boolean | null;
}

/**
 * GET prospect-options: the grouped slice options, one list per axis.
 */
export interface CharacterProspectOptions {
	tags: ProspectOption[];
	mobs: ProspectOption[];
	weapons: ProspectOption[];
}

/**
 * The record a manual rank calibration returns.
 */
export interface CodexCalibrateResult {
	speciesName: string;
	rank: number;
}

/**
 * The record a rank claim (or its reversal) returns.
 */
export interface CodexClaimResult {
	speciesName: string;
	rank: number;
	skillName: string;
	pedValue: number;
}

/**
 * One recorded mastery claim in a species' breakdown, in claim order
 * (`mastery_level` is the 1-based per-species sequence number).
 */
export interface CodexMasteryClaim {
	masteryLevel: number;
	skillName: string;
	pedValue: number;
}

/**
 * The record a mastery claim (or its reversal) returns.
 * `mastery_level` is the per-species claim sequence number (the Nth
 * mastery claim for that species).
 */
export interface CodexMasteryClaimResult {
	speciesName: string;
	masteryLevel: number;
	skillName: string;
	pedValue: number;
}

/**
 * One meta attribute with its current calibrated level.
 */
export interface CodexMetaAttribute {
	name: string;
	currentLevel: number | null;
}

/**
 * The record a meta claim returns.
 */
export interface CodexMetaClaimResult {
	attributeName: string;
	pedValue: number;
}

/**
 * One requested profession's share of a skill option's contribution
 * (professions with no weight on the skill are omitted).
 */
export interface CodexProfessionContribution {
	profession: string;
	profContribution: number;
}

/**
 * One rank in a species' breakdown: the derived cost / reward / category
 * fields, plus the player's claim state for that rank. Field order is
 * the wire order (the breakdown's own fields, then the claim overlay).
 */
export interface CodexRank {
	rank: number;
	category: string;
	cost: number;
	rewardPed: number;
	cat4Bonus: boolean;
	cat4RewardPed?: number | null;
	skills: string[];
	cat4Skills: string[];
	claimed: boolean;
	claimedSkill: string | null;
	claimedPed: number | null;
	isNext: boolean;
}

/**
 * What a codex recommendation ranks by. A closed vocabulary: the
 * bindings expose only these two, so an out-of-vocabulary `target` is
 * unrepresentable rather than validated.
 */
export type CodexRecommendTarget = 'profession' | 'hp';

/**
 * One skill option in a rank recommendation: the reward it grants, the
 * levels that buys at the current point on the curve, and the profession
 * / HP contribution used to rank the list. The weight and contribution
 * sum over the requested professions; `profession_contributions` carries
 * the per-profession split.
 */
export interface CodexSkillOption {
	skillName: string;
	category: string;
	rewardPed: number;
	currentLevel: number | null;
	levelsGained: number;
	professionWeight: number;
	profContribution: number;
	professionContributions: CodexProfessionContribution[];
	hpIncrease: number | null;
	hpGain: number;
	recommendRank: number | null;
}

/**
 * One species in the codex listing: its base cost, the player's current
 * rank, and the next rank's derived category and cost (all `null` once
 * rank 25 is reached).
 */
export interface CodexSpecies {
	name: string;
	baseCost: number;
	codexType: string | null;
	currentRank: number;
	nextRank: number | null;
	nextCategory: string | null;
	nextCost: number | null;
	masteryLevel: number;
}

/**
 * A species' full 25-rank breakdown, cross-referenced with the player's
 * claims and current rank.
 */
export interface CodexSpeciesRanks {
	speciesName: string;
	baseCost: number;
	codexType: string | null;
	currentRank: number;
	masteryLevel: number;
	masteryClaims: CodexMasteryClaim[];
	ranks: CodexRank[];
}

/**
 * The compaction result: the path of the written compacted copy and its
 * size in bytes.
 */
export interface CompactResult {
	path: string;
	bytes: number;
}

/**
 * GET stats: current HP and the top five professions.
 */
export interface ComputedCharacterStats {
	hp: number;
	topProfessions: StatProfession[];
}

/**
 * The calibration flow's phase, as the closed wire vocabulary.
 */
export type CoordCalibrationPhase = 'idle' | 'awaitTopLeft' | 'awaitBottomRight';

/**
 * The calibration surface's assembled state: the flow phase, the
 * persisted region (null until a calibration completed), and the
 * validation read echoed after the last completion.
 */
export interface CoordCalibrationStatus {
	phase: CoordCalibrationPhase;
	region: CoordRegionDto | null;
	lastValidation: CoordScanResult | null;
}

/**
 * The persisted capture rectangle, in screen coordinates.
 */
export interface CoordRegionDto {
	x: number;
	y: number;
	w: number;
	h: number;
}

/**
 * One coordinate scan's answer: `status` names the outcome precisely
 * (a wrong read never masquerades as a position), and the extras ride
 * where the outcome carries them (the `CaptureResult` convention):
 * coordinates on `read` and `implausible`, the raw capture text only
 * on `unreadable` (where the UI shows it); a successful read's text is
 * its digits, so the parsed coordinates already carry everything and
 * the boundary hands the webview no more screen text than it needs.
 */
export interface CoordScanResult {
	status: CoordScanStatus;
	lon?: number | null;
	lat?: number | null;
	altitude?: number | null;
	rawText?: string | null;
	confidence?: number | null;
}

/**
 * The closed vocabulary of a coordinate scan's outcome.
 */
export type CoordScanStatus = 'read' | 'noRegion' | 'captureFailed' | 'engineUnavailable' | 'unreadable' | 'implausible';

/**
 * The session-detail cost split.
 */
export interface CostBreakdown {
	weaponCost: number;
	healCost: number;
	enhancerCost: number;
	armourCost: number;
	/** Harvesting (tree cutting) swing decay. */
	harvestCost: number;
}

/**
 * One line of a cost breakdown.
 */
export interface CostBreakdownLine {
	component: string;
	costPec: number;
	markupMultiplier: number;
	effectiveCostPec: number;
}

/**
 * The crash-reporting opt-in state, a one-key body.
 */
export interface CrashReportingStatus {
	crash_reporting_enabled: boolean;
}

/**
 * The per-family cycled-cost split.
 */
export interface CycledBreakdown {
	weapon: number;
	healing: number;
	enhancer: number;
	armour: number;
	dangling: number;
}

/**
 * One configured component of a stored weapon setup.
 */
export interface EquipmentComponent {
	catalogId: string | null;
	name: string;
	decay: number;
	ammoBurn: number;
	markupPercent: number;
	isLimited: boolean;
	damageEnhancers: number;
}

/**
 * The expanded library-entry detail.
 */
export interface EquipmentDetail {
	id: string;
	weapon: EquipmentComponent;
	amplifier: EquipmentComponent | null;
	scope: EquipmentComponent | null;
	absorber: AbsorberComponent | null;
	/** The Mindforce implant powering the item, when configured; shares the absorber component shape (its absorption is the decay share it takes per use). */
	implant: AbsorberComponent | null;
	costBreakdown: CostBreakdownLine[];
	totalCostPerUse: number;
}

/**
 * The stored equipment classes. `Tool` is a harvesting tool (tree
 * cutting): a single-entity item like a healing tool, costed as pure
 * decay per swing with no ammo.
 */
export type EquipmentKind = 'weapon' | 'healing' | 'consumable' | 'tool';

/**
 * An add or update request. Field names stay in the request casing the
 * frontend has always sent.
 */
export interface EquipmentRequest {
	type: EquipmentKind;
	catalog_id?: string | null;
	name?: string | null;
	amp_catalog_id?: string | null;
	scope_catalog_id?: string | null;
	absorber_catalog_id?: string | null;
	weapon_markup?: number;
	amp_markup?: number;
	scope_markup?: number;
	absorber_markup?: number;
	damage_enhancers?: number;
	implant_catalog_id?: string | null;
	implant_markup?: number;
}

/**
 * A catalogue search hit.
 */
export interface EquipmentSearchHit {
	catalogId: string | null;
	name: string;
	/** Decay per use, PEC. */
	decay: number;
	/** Ammo burn per use, PEC (catalogue units / 100). */
	ammoBurn: number;
	/** Decay-absorption share, percent, for absorbers/extenders and Mindforce implants; null for catalogue rows without one. */
	absorptionPercent: number | null;
	isLimited: boolean;
}

/**
 * A library entry in the list shape.
 */
export interface EquipmentSummary {
	id: string;
	name: string;
	type: EquipmentKind;
	amplifierName: string | null;
	costPerUse: number;
	damageMin: number | null;
	damageMax: number | null;
	reloadSeconds: number | null;
	isLimited: boolean;
	/** 1 = base item, 2 = amplified, 3 = fully accessorised. */
	enrichmentLevel: number;
}

/**
 * A skill the path optimizer left out, with the reason.
 */
export interface ExcludedSkill {
	name: string;
	weight: number;
	reason: string;
}

/**
 * The game-connection block: the configured chat-log path, whether it
 * currently resolves to a file, and the player name.
 */
export interface GameConnection {
	chatLogPath: string;
	chatLogValid: boolean;
	playerName: string;
}

/**
 * A harvest-guardrail disagreement on the snapshot: the tool the loot
 * evidence expects for the board-output class, the tool the hotbar believed
 * (null when none was equipped), and when the evidence arrived.
 */
export interface HarvestGuardrailAlert {
	expectedTool: string;
	observedTool: string | null;
	treeSize: TreeSizeName;
	atEpoch: number;
}

/**
 * The harvest-guardrail block in a settings update. Field names stay
 * in the stored snake_case the config writer re-normalises.
 */
export interface HarvestGuardrailInput {
	enabled?: boolean;
	short_tool_id?: number | null;
	long_tool_id?: number | null;
	huge_tool_id?: number | null;
}

/**
 * The harvest-guardrail block: the enabled flag and the intended tool
 * id per board-output class (null while a class has no intended tool).
 */
export interface HarvestGuardrailSettings {
	enabled: boolean;
	shortToolId: number | null;
	longToolId: number | null;
	hugeToolId: number | null;
}

/**
 * One item in an activity's harvest loot composition: realised TT only.
 * The market markup column is merged in at the frontend from the
 * market layer, never joined into this accounting DTO.
 */
export interface HarvestLootItem {
	itemName: string;
	quantity: number;
	valuePed: number;
}

/**
 * A session's harvesting (tree cutting) totals: every swing is a
 * counted event (successes arrive as wood loot groups, fails as the
 * explicit harvest-fail line).
 */
export interface HarvestSummary {
	swings: number;
	successes: number;
	lootTt: number;
	cost: number;
}

/**
 * One effective yield activity and the loot it produced.
 */
export interface HarvestTierComparison {
	yieldTier: HarvestYieldTier;
	swings: number;
	cycled: number;
	returns: number;
	lootRate: number;
	lootItems: HarvestLootItem[];
}

/**
 * Tree Cutting's durable source-activity vocabulary.
 */
export type HarvestYieldTier = 'short' | 'long' | 'huge' | 'unknown';

/**
 * One latency-histogram bucket: the inclusive upper bound in
 * microseconds (`None` for the final overflow bucket) and its count.
 * Mirrors `eo_wire::metrics::Bucket`.
 */
export interface HistogramBucket {
	bound_us: number | null;
	count: number;
}

/**
 * A point-in-time read of one latency histogram: the total count, the
 * microsecond sum (so a mean is recoverable), and the per-bucket counts.
 * Mirrors `eo_wire::metrics::HistogramSnapshot`.
 */
export interface HistogramSnapshot {
	count: number;
	sum_us: number;
	buckets: HistogramBucket[];
}

/**
 * One attribute row of the HP optimizer.
 */
export interface HpOptimizerAttribute {
	name: string;
	hpIncrease: number;
	currentLevel: number;
	levelsPerHp: number;
}

/**
 * GET hp-optimizer: the HP-per-PED breakdown across contributing
 * skills and attributes.
 */
export interface HpOptimizerResult {
	currentHp: number;
	skills: HpOptimizerSkill[];
	attributes: HpOptimizerAttribute[];
}

/**
 * One skill row of the HP optimizer.
 */
export interface HpOptimizerSkill {
	name: string;
	hpIncrease: number;
	currentLevel: number;
	levelsPerHp: number;
	pedPerHp: number;
	hpPerPed: number;
	codexCategory: string | null;
	codexDivisor: number | null;
}

/**
 * One inventory item.
 */
export interface InventoryItem {
	id: string;
	name: string;
	ttValue: number;
	markupPaid: number;
	notes: string | null;
	acquiredAt: string;
}

/**
 * An inventory-item create payload (snake_case, matching the frontend
 * request shape). `notes` / `acquired_at` are optional; an empty / absent
 * `acquired_at` defaults to today's UTC date.
 */
export interface InventoryItemInput {
	name: string;
	tt_value: number;
	markup_paid: number;
	notes?: string | null;
	acquired_at?: string | null;
}

/**
 * An inventory-item patch: only present (`Some`) fields update.
 */
export interface InventoryPatch {
	name?: string | null;
	tt_value?: number | null;
	markup_paid?: number | null;
	notes?: string | null;
}

/**
 * An inventory-sale payload.
 */
export interface InventorySellInput {
	sale_price: number;
	description?: string | null;
	sold_at?: string | null;
}

/**
 * The result of selling an inventory item: the emitted ledger entry
 * (`null` for a zero-delta sale) and the sold item.
 */
export interface InventorySellResult {
	ledgerEntry: LedgerItem | null;
	soldItem: InventoryItem;
}

/**
 * A ledger-entry create payload.
 */
export interface LedgerEntryInput {
	date: string;
	type: string;
	description: string;
	amount: number;
	tag: string;
}

/**
 * One ledger entry.
 */
export interface LedgerItem {
	id: string;
	date: string;
	type: LedgerKind;
	description: string;
	amount: number;
	tag: string;
}

/**
 * A ledger entry's accounting class. Writes validate to exactly these
 * two values; the read side classifies anything else as an expense,
 * mirroring the binary styling check the frontend has always applied.
 */
export type LedgerKind = 'expense' | 'markup';

/**
 * A page of ledger entries plus the opaque cursor for the next page
 * (`null` on the last page) and the whole-ledger row count, so a pager
 * can report true bounds while loading windows on demand: the keyset
 * `X-Next-Cursor` header folded into the typed return, since a command
 * answers one structured payload.
 */
export interface LedgerPage {
	entries: LedgerItem[];
	nextCursor: string | null;
	total: number;
}

/**
 * One ledger preset (a reusable ledger-entry template).
 */
export interface LedgerPreset {
	id: string;
	name: string;
	type: LedgerKind;
	description: string;
	amount: number;
	tag: string;
}

/**
 * A ledger-preset create payload.
 */
export interface LedgerPresetInput {
	name: string;
	type: string;
	description: string;
	amount: number;
	tag: string;
}

/**
 * The whole-ledger summary for a period: the per-tag markup (gain) and
 * expense (loss) totals over every entry in the window, independent of
 * the paginated list. The Ledger tab's net-impact and source cards read
 * this instead of folding the loaded page window.
 */
export interface LedgerSummary {
	gains: Record<string, number>;
	losses: Record<string, number>;
}

/**
 * One aggregated loot line.
 */
export interface LootEntry {
	name: string;
	quantity: number;
	ttValue: number;
}

/**
 * The loot-item activate / deactivate result.
 */
export interface LootItemEditResult {
	sessionId: string;
	itemName: string;
	affectedRows: number;
	totalValueDelta: number;
	sessionTotalReturns: number;
}

/**
 * The losses breakdown: tracking cost, its cycled split, and the ledger
 * expenses.
 */
export interface LossesBreakdown {
	trackingCost: number;
	cycledBreakdown: CycledBreakdown;
	ledger: Record<string, number>;
}

/**
 * The manual-mob-lock acknowledgement.
 */
export interface ManualMobLockResult {
	mobName: string;
	species: string;
	maturity: string;
}

/**
 * One manual-mob autocomplete suggestion.
 */
export interface ManualMobSuggestion {
	display: string;
	species: string;
	maturity: string;
}

/**
 * One stored cartography pin. Coordinates are game units; `radius_m`
 * null marks an exact point, a value an area pin of that radius in
 * metres; `session_id` backlinks the tracked session the pin was
 * dropped during, when any.
 */
export interface MapPin {
	id: number;
	planet: string;
	lon: number;
	lat: number;
	altitude: number | null;
	name: string;
	icon: string;
	kind: string;
	radiusM: number | null;
	notes: string | null;
	sessionId: string | null;
	mapViewId: number | null;
	/** Epoch seconds. */
	createdAt: number;
	/** Epoch seconds of the pin's most recent confirmed visit, if any. */
	lastVisitedAt: number | null;
	/** Epoch seconds until which the most recent visit keeps the pin on cooldown, if any. */
	cooldownUntil: number | null;
	/** The palette configuration this pin is an instance of, if any. */
	pinConfigId: number | null;
	/** The pin's colour, from its configuration (generic or special-active). */
	colour: string | null;
	/** The special-tree on-cooldown colour, from its configuration. */
	cooldownColour: string | null;
	/** The configuration's category (`generic` / `special`), if any. */
	category: string | null;
	/** The configuration's special kind (`tree`), if any. */
	specialKind: string | null;
}

/**
 * A new pin's fields (id and creation time are assigned server-side).
 */
export interface MapPinInput {
	planet: string;
	lon: number;
	lat: number;
	altitude?: number | null;
	name: string;
	icon: string;
	kind: string;
	radiusM?: number | null;
	notes?: string | null;
	sessionId?: string | null;
	mapViewId?: number | null;
	/** The palette configuration this pin instantiates, if any. */
	pinConfigId?: number | null;
	/** Explicit confirmation that a pin may be created within the duplicate-advisory radius of an existing pin. */
	allowNearby?: boolean;
}

/**
 * A partial pin update: absent fields stay untouched. The nullable
 * fields (altitude, radius, notes) are double options so an explicit
 * `null` (clear it) stays distinct from an absent field.
 */
export interface MapPinPatch {
	lon?: number | null;
	lat?: number | null;
	altitude?: number | null;
	name?: string | null;
	icon?: string | null;
	kind?: string | null;
	radiusM?: number | null;
	notes?: string | null;
}

/**
 * One user-named pin set over a planet map. Default is represented by
 * a null view id and therefore has no row of its own.
 */
export interface MapView {
	id: number;
	planet: string;
	name: string;
	createdAt: number;
}

/**
 * The break-even readout: the player's looter professions and every
 * library weapon's modelled break-even markup against each of them.
 */
export interface MarketBreakEven {
	looters: MarketLooterLevel[];
	weapons: MarketWeaponBreakEven[];
}

/**
 * One (weapon, looter) break-even cell: the modelled TT-return rate
 * and the overall loot markup that loadout needs to break even. Both
 * figures are MODELLED ESTIMATES (community returns model, roughly a
 * one-percentage-point error bar), never measured rates.
 */
export interface MarketBreakEvenCell {
	looterName: string;
	ttReturnPct: number;
	breakEvenMarkupPct: number;
}

/**
 * A committed paste: the submission it created.
 */
export interface MarketCommitResult {
	submissionId: number;
	itemCount: number;
	skippedCount: number;
	/** Epoch seconds. */
	observedAt: number;
}

/**
 * The most recent accepted paste as a contributable batch: exactly
 * what an opted-in contributor shares, nothing more. The frontend
 * owns the send, strictly behind the contribution opt-in.
 */
export interface MarketContributionBatch {
	/** Epoch seconds of the submission. */
	observedAt: number;
	items: MarketContributionItem[];
}

/**
 * One item of a contributable batch: the pasted readings verbatim,
 * by horizon name.
 */
export interface MarketContributionItem {
	itemName: string;
	tier: number;
	day: MarketReading;
	week: MarketReading;
	month: MarketReading;
	year: MarketReading;
	decade: MarketReading;
}

/**
 * The estimated market signals for the harvest-looted items, plus the
 * nanocube recycling floor. Markup is item-intrinsic, so this is a flat
 * per-item list; the frontend merges it with the per-tool composition,
 * derives holding-independent market opportunity, and computes the
 * current-market aggregates. Estimated markup is informational only,
 * never a realised figure.
 */
export interface MarketHarvestData {
	/** The nanocube item's resolved markup (percent): the universal recycling floor. Null when no nanocube observation exists (the frontend then falls back to a constant). */
	nanocubeMarkupPct: number | null;
	items: MarketHarvestItem[];
}

/**
 * One horizon's reading for a harvest item: its markup (null where the
 * game reported N/A) and TT turnover (PED).
 */
export interface MarketHarvestHorizon {
	/** "day" | "week" | "month" | "year". */
	horizon: string;
	markupPct: number | null;
	salesPed: number;
}

/**
 * One harvest-looted item's resolved market signals plus the per-horizon
 * breakdown. The resolved markup/horizon/sales are the display default
 * and market-opportunity input (week preferred, then month, then year;
 * all null when no observation covers the item). `readings` carries every
 * horizon (day, week, month, year) for the detail view.
 */
export interface MarketHarvestItem {
	itemName: string;
	markupPct: number | null;
	horizon: string | null;
	salesPed: number | null;
	/** Every horizon's reading, ordered day, week, month, year. */
	readings: MarketHarvestHorizon[];
}

/**
 * One point of an item's per-horizon history, oldest first.
 */
export interface MarketHistoryPoint {
	/** Epoch seconds. */
	observedAt: number;
	markupPct: number | null;
	salesPed: number;
}

/**
 * One of the export's five aggregation horizons.
 */
export type MarketHorizon = 'day' | 'week' | 'month' | 'year' | 'decade';

/**
 * One looter profession and its believed-current level.
 */
export interface MarketLooterLevel {
	name: string;
	level: number;
}

/**
 * One species' estimated-markup row: recorded loot composition
 * TT-weighted by the latest markup observations on one horizon.
 * Coverage keeps a thin sample honest: the estimate weights only the
 * covered TT, and the row says how much that is.
 */
export interface MarketMobRankingRow {
	mobSpecies: string;
	lootTt: number;
	coveredTt: number;
	itemCount: number;
	coveredItemCount: number;
	estMarkupPct: number | null;
}

/**
 * One overview row: an item's latest readings (from the most recent
 * submission that carried it) and when they were observed.
 */
export interface MarketOverviewRow {
	itemName: string;
	tier: number;
	/** Epoch seconds of the submission the readings came from (the staleness signal). */
	observedAt: number;
	day: MarketReading;
	week: MarketReading;
	month: MarketReading;
	year: MarketReading;
	decade: MarketReading;
}

/**
 * The parse preview: what a commit of the same text would store, and
 * what it would ignore.
 */
export interface MarketPastePreview {
	rows: MarketPastePreviewRow[];
	skipped: MarketSkippedLine[];
}

/**
 * One parsed item row: the five horizon readings by name.
 */
export interface MarketPastePreviewRow {
	itemName: string;
	tier: number;
	day: MarketReading;
	week: MarketReading;
	month: MarketReading;
	year: MarketReading;
	decade: MarketReading;
}

/**
 * One horizon's reading: the markup percentage (null where the game
 * reported N/A, meaning no sales in that horizon) and the sales
 * volume in PED.
 */
export interface MarketReading {
	markupPct: number | null;
	salesPed: number;
}

/**
 * One line the parser could not use, for the review flow.
 */
export interface MarketSkippedLine {
	/** 1-based line number within the paste. */
	lineNumber: number;
	content: string;
	reason: string;
}

/**
 * One library weapon's break-even row: its catalogue efficiency (null
 * when the bundled catalogue does not carry the weapon) and the cells
 * across the player's looter professions.
 */
export interface MarketWeaponBreakEven {
	name: string;
	efficiencyPct: number | null;
	cells: MarketBreakEvenCell[];
}

/**
 * A point-in-time read of the process telemetry registry: event
 * throughput, the OCR / database latency histograms, and the
 * resource-drift gauges. Counts and durations only; no PII. Mirrors
 * `eo_wire::metrics::MetricsSnapshot` field-for-field, so
 * `serde_json::to_string` yields identical bytes (pinned in the tests below).
 */
export interface MetricsSnapshot {
	events_published: number;
	ocr_latency: HistogramSnapshot;
	db_query_latency: HistogramSnapshot;
	rss_bytes: number;
	handle_count: number;
}

/**
 * One per-mob breakdown row.
 */
export interface MobBreakdownRow {
	currentName: string;
	originalName: string | null;
	killCount: number;
}

/**
 * One row of the per-mob activity comparison.
 */
export interface MobComparison {
	mobName: string;
	sessions: number;
	kills: number;
	hours: number;
	cycled: number;
	pesPer100Ped: number;
	lootRate: number;
}

/**
 * The mob rename / restore result.
 */
export interface MobEditResult {
	sessionId: string;
	mobName: string;
	killCount: number;
}

/**
 * The legacy exclusive-capture input mode recorded on pre-facet
 * session rows; read-only vocabulary for labelling those sessions
 * (facet-era rows all read as `mob`, the column default).
 */
export type MobEntryMode = 'mob' | 'tag';

/**
 * One month of the Overview monthly breakdown.
 */
export interface MonthlyEntry {
	month: string;
	lootTt: number;
	pes: number;
	codexPes: number;
	questPes: number;
	ledgerGains: Record<string, number>;
	trackingCost: number;
	ledgerLosses: Record<string, number>;
}

/**
 * One row of the per-session-name activity comparison (the designated
 * axis; legacy tag-mode sessions appear under their migrated names).
 */
export interface NameComparison {
	sessionName: string;
	sessions: number;
	kills: number;
	hours: number;
	cycled: number;
	pesPer100Ped: number;
	lootRate: number;
}

export interface NavigationPositionResult {
	status: NavigationPositionStatus;
	run: NavigationRun | null;
}

export type NavigationPositionStatus = 'updated' | 'noActiveRun' | 'paused' | 'noRegion' | 'captureFailed' | 'engineUnavailable' | 'unreadable' | 'implausible' | 'ambiguous' | 'outOfTolerance';

export interface NavigationRun {
	id: number;
	planet: string;
	mapViewId: number | null;
	mapViewName: string | null;
	status: NavigationRunStatus;
	startLon: number;
	startLat: number;
	currentLon: number;
	currentLat: number;
	lastPositionAt: number | null;
	hopCount: number;
	hotkey: string;
	updatedAt: number;
	distanceToActive: number | null;
	/** Degrees clockwise from north. */
	bearingDegrees: number | null;
	pendingHarvest: PendingHarvest | null;
	stops: NavigationStop[];
}

export type NavigationRunStatus = 'active' | 'paused' | 'completed' | 'ended';

export interface NavigationStop {
	id: number;
	pinId: number;
	ordinal: number;
	status: NavigationStopStatus;
	name: string;
	icon: string;
	lon: number;
	lat: number;
	completedAt: number | null;
	completionSource: string | null;
}

export type NavigationStopStatus = 'pending' | 'active' | 'visited' | 'skipped';

export interface NearbyMapPin {
	pin: MapPin;
	distance: number;
}

/**
 * One notable event in a session detail.
 */
export interface NotableEvent {
	type: NotableEventCategory;
	eventType: NotableEventType;
	target: string | null;
	item: string | null;
	value: number;
}

/**
 * The broad notable-event family (drives styling on the frontend).
 */
export type NotableEventCategory = 'global' | 'hof' | 'quest' | 'warning';

/**
 * The canonical notable-event subtype the services store.
 */
export type NotableEventType = 'global_kill' | 'global_item' | 'hof_kill' | 'hof_item' | 'quest_started' | 'quest_completed' | 'quest_completed_pes';

/**
 * One attribute row of the profession / path optimizer.
 */
export interface OptimizerAttribute {
	name: string;
	weight: number;
	currentLevel: number;
	contributionFactor: number;
}

/**
 * One skill row of the profession optimizer.
 */
export interface OptimizerSkill {
	name: string;
	weight: number;
	currentLevel: number;
	levelsNeeded: number;
	pedToNextLevel: number;
	codexCategory: string | null;
	codexDivisor: number | null;
}

/**
 * GET overlay-position: the persisted overlay window coordinates (null
 * until first placed).
 */
export interface OverlayPosition {
	x: number | null;
	y: number | null;
}

/**
 * One allocation of the path optimizer.
 */
export interface PathAllocation {
	name: string;
	weight: number;
	currentLevel: number;
	levelsToGain: number;
	pedCost: number;
	newLevel: number;
	codexCategory: string | null;
	codexDivisor: number | null;
}

/**
 * GET profession-path-optimizer: the greedy allocation for a target
 * level or a PED budget. `inputTargetLevel` / `inputPedBudget` echo the
 * mode (exactly one is non-null); `error` marks a missing profession.
 */
export interface PathOptimizerResult {
	allocations: PathAllocation[];
	attributes: OptimizerAttribute[];
	profession: string;
	mode: string;
	inputTargetLevel: number | null;
	inputPedBudget: number | null;
	currentLevel: number;
	endLevel: number;
	professionLevelsGained: number;
	totalPed: number;
	excluded: ExcludedSkill[];
	error?: string | null;
}

/**
 * A harvest detected beyond the arrival radius, awaiting the player's confirm
 * or dismiss in the overlay. Names the proposed (active) tree and how far the
 * harvest read was from it.
 */
export interface PendingHarvest {
	name: string;
	distance: number;
}

/**
 * One palette entry: a pin *type* scoped to a `(planet, map view)` preset.
 * `category` is `generic` or `special`; the only special `kind` so far is
 * `tree`, which carries a `cooldownColour`. `colour` is the generic colour or
 * the special-active colour. `placedCount` is how many pins reference it.
 */
export interface PinConfig {
	id: number;
	planet: string;
	mapViewId: number | null;
	label: string;
	category: string;
	specialKind: string | null;
	icon: string;
	radiusM: number | null;
	colour: string;
	cooldownColour: string | null;
	ordinal: number;
	/** Epoch seconds. */
	createdAt: number;
	placedCount: number;
}

export interface PinConfigEditInput {
	label: string;
	category: string;
	specialKind?: string | null;
	icon: string;
	radiusM?: number | null;
	colour: string;
	cooldownColour?: string | null;
}

export interface PinConfigInput {
	planet: string;
	mapViewId?: number | null;
	label: string;
	category: string;
	specialKind?: string | null;
	icon: string;
	radiusM?: number | null;
	colour: string;
	cooldownColour?: string | null;
}

/**
 * One planet/instance map in the bundled catalogue. `calibration` is
 * null for a view-only map (displayable, but coordinates cannot be
 * placed on it); `technical_name` is null when the in-game waypoint
 * name is unknown.
 */
export interface PlanetMap {
	name: string;
	technicalName: string | null;
	imageMime: string;
	imageWidthPx: number;
	imageHeightPx: number;
	calibration: PlanetMapCalibration | null;
}

/**
 * A map's coordinate window in game units: the plausibility gate for
 * any coordinate claimed to lie on it.
 */
export interface PlanetMapBounds {
	lonMin: number;
	lonMax: number;
	latMin: number;
	latMax: number;
}

/**
 * A calibrated map's placement on the global tile grid, with the
 * per-axis pixel scales the frontend renders through.
 */
export interface PlanetMapCalibration {
	tileOriginX: number;
	tileOriginY: number;
	tileWidth: number;
	tileHeight: number;
	unitsPerPixelX: number;
	unitsPerPixelY: number;
	bounds: PlanetMapBounds;
}

/**
 * Per-playlist analytics in the wire shape
 * (`_format_playlist_analytics`).
 */
export interface PlaylistAnalyticsRow {
	playlistId: string;
	playlistName: string;
	questCount: number;
	longHorizonQuestCount: number;
	matchedSessions: number;
	totalRewardPed: number;
	totalImmediateRewardPed: number;
	totalBonusRewardPed: number;
	totalPesReward: number;
	totalImmediatePesReward: number;
	totalBonusPesReward: number;
	totalExpectedRewardPed: number;
	totalExpectedImmediateRewardPed: number;
	totalExpectedBonusRewardPed: number;
	totalDurationSec: number;
	totalWeaponCost: number;
	totalHealCost: number;
	totalEnhancerCost: number;
	totalArmourCost: number;
	totalLootTt: number;
	totalPes: number;
}

/**
 * A playlist create or update payload, in the frontend's snake_case
 * casing. The sole client sends `name` / `planet` / `estimated_minutes`
 * / `items` for both operations (never `quest_ids`); the service derives
 * membership from `items` whenever it is present, so the facade sends
 * exactly those keys and omits the vestigial `quest_ids`.
 */
export interface PlaylistInput {
	name: string;
	planet?: string;
	estimated_minutes?: number;
	items?: PlaylistItemInput[];
}

/**
 * One classified slot in a playlist's wire shape.
 */
export interface PlaylistItem {
	questId: string;
	description: string | null;
	groupType: PlaylistItemGroup;
}

/**
 * Which playlist group a quest slot belongs to. The serialised forms
 * are byte-identical to the strings they replace; the input side
 * (`PlaylistItemInput`) deliberately stays a plain string so its
 * service-level validation and error replies are untouched.
 */
export type PlaylistItemGroup = 'immediate' | 'long_horizon';

/**
 * One classified quest slot in a playlist create/update.
 */
export interface PlaylistItemInput {
	quest_id: number;
	description?: string | null;
	group_type?: string;
}

/**
 * One profession row.
 */
export interface ProfessionLevel {
	name: string;
	level: number;
	anchorLevel: number | null;
	gainSinceAnchor: number | null;
	category: string;
}

/**
 * GET profession-optimizer: the cheapest-skill breakdown to the next
 * profession level. On a missing profession the declared tail fields
 * stay unset and only `error` accompanies the empty lists.
 */
export interface ProfessionOptimizerResult {
	skills: OptimizerSkill[];
	attributes: OptimizerAttribute[];
	profession?: string | null;
	currentLevel?: number | null;
	nextLevel?: number | null;
	gap?: number | null;
	error?: string | null;
}

/**
 * One grouped Prospect slice option.
 */
export interface ProspectOption {
	value: string;
	label: string;
	sessions: number;
	kills: number;
	hours: number;
	cycledPed: number;
}

/**
 * The Prospect forecast query. `sliceValue` is required for every slice
 * but `global`; `markupUplift` defaults to zero.
 */
export interface ProspectQuery {
	profession: string;
	targetLevel: number;
	sliceType: ProspectSliceType;
	sliceValue?: string | null;
	markupUplift?: number;
}

/**
 * GET prospect: the forecast. `error` is present only on the soft-error
 * paths (the frontend renders it inline rather than throwing); every
 * other field is always present, so the declared order below is the
 * wire order.
 */
export interface ProspectResult {
	error?: string | null;
	rows: ProspectRow[];
	warnings: string[];
	profession: string;
	sliceType: string;
	sliceValue: string | null;
	markupUplift: number;
	currentLevel: number;
	targetLevel: number;
	projectedCycledPed: number;
	projectedHours: number;
	expectedLootTt: number;
	expectedNetTtBurn: number;
	speculativeLootTt: number | null;
	speculativeNetTtBurn: number | null;
	sample: ProspectSample;
}

/**
 * One skill/attribute row of a Prospect forecast.
 */
export interface ProspectRow {
	name: string;
	isAttribute: boolean;
	weight: number;
	currentLevel: number;
	observedShare: number;
	observedRate: number;
	projectedGain: number;
	projectedEndLevel: number;
	professionContribution: number;
	relevant: boolean;
}

/**
 * The observed sample a Prospect forecast projects from. The internal
 * `skillShares` / `attributeRates` maps are computed but not surfaced
 * (no consumer reads them; dropped with the migration).
 */
export interface ProspectSample {
	sessions: number;
	kills: number;
	hours: number;
	cycledPed: number;
	lootTt: number;
	pes: number;
	attributeLevels: number;
	cycledPerHour: number;
	lootPerHour: number;
	returnRate: number;
	pesPerPed: number;
	lootTtPerPed: number;
}

/**
 * The slice a Prospect forecast aggregates over. A closed vocabulary:
 * the bindings expose only these four, so the old out-of-vocabulary 422
 * is unrepresentable rather than validated.
 */
export type ProspectSliceType = 'global' | 'tag' | 'mob' | 'weapon';

/**
 * A quest in the wire shape (`_format_quest` key for key). Ids are
 * stringified; `rewardDescription` / `notes` collapse null-or-empty to
 * `""`; `rewardIsSkill` is the boolean of the stored int flag.
 */
export interface Quest {
	id: string;
	name: string;
	category: string | null;
	targetMobs: string[];
	planet: string;
	waypoint: string | null;
	cooldownDurationHours: number | null;
	cooldownExpiresAt: string | null;
	reward: number | null;
	rewardIsSkill: boolean;
	expectedRewardMarkupPercent: number | null;
	rewardDescription: string;
	notes: string;
	chainName: string | null;
	chainPosition: number | null;
	chainTotal: number | null;
	playlistIds: string[];
	/** A fractional epoch-seconds timestamp (the tracker's clock is sub-second), null while the quest is not in progress. */
	startedAt: number | null;
}

/**
 * Per-quest analytics in the wire shape (`_format_quest_analytics`).
 * The reward and cost columns are model-float coerced and rounded; the
 * session count is an integer; the markup passes through raw.
 */
export interface QuestAnalyticsRow {
	questId: string;
	questName: string;
	planet: string;
	category: string | null;
	rewardPed: number;
	rewardIsSkill: boolean;
	expectedRewardMarkupPercent: number | null;
	totalExpectedRewardPed: number;
	linkedSessions: number;
	totalDurationSec: number;
	totalWeaponCost: number;
	totalHealCost: number;
	totalEnhancerCost: number;
	totalArmourCost: number;
	totalLootTt: number;
	totalPes: number;
}

/**
 * A quest create or update payload. One DTO serves both operations, in
 * the frontend's snake_case field casing: the sole client sends the
 * full field set for both create and update (nulls explicit), so every
 * field is serialised to the service `Value` (present-null clears a
 * column on update, exactly as the exclude-unset contract did for the
 * only payload the client ever produced). `update_quest` ignores the
 * `mobs` key by design, so a full payload is behaviour-identical to the
 * HTTP path either way.
 */
export interface QuestInput {
	name: string;
	planet?: string;
	category?: string | null;
	waypoint?: string | null;
	cooldown_hours?: number | null;
	reward_ped?: number | null;
	reward_is_skill?: boolean;
	expected_reward_markup_percent?: number | null;
	reward_description?: string | null;
	notes?: string | null;
	chain_name?: string | null;
	chain_position?: number | null;
	chain_total?: number | null;
	mobs?: string[];
}

/**
 * Why the quest-link suggestion took its shape.
 */
export type QuestLinkReason = 'single_quest' | 'exact_playlist' | 'no_completions' | 'unclean' | 'ambiguous_playlist' | 'declined' | 'already_linked';

/**
 * What the quest-link suggestion proposes.
 */
export type QuestLinkSuggestionType = 'quest' | 'playlist' | 'none';

/**
 * A playlist in the wire shape (`_format_playlist`). Membership arrives
 * pre-classified from the service; ids are stringified.
 */
export interface QuestPlaylist {
	id: string;
	name: string;
	planet: string;
	estimatedMinutes: number;
	questIds: string[];
	immediateQuestIds: string[];
	longHorizonQuestIds: string[];
	items: PlaylistItem[];
}

export type RadarCalibrationStatus = 'idle' | 'awaitCentre' | 'awaitNorthEdge';

export interface RadarGeometry {
	centreX: number;
	centreY: number;
	northX: number;
	northY: number;
	radiusPx: number;
	displayScale: number;
}

/**
 * One yield tier's net realised markup from confirmed sales.
 */
export interface RealisedTierMarkup {
	yieldTier: HarvestYieldTier;
	netMarkup: number;
}

/**
 * The rebuild-and-verify report: whether every projection rebuilt
 * byte-identically, and the per-table verdicts in their stable order.
 * `allMatched` keeps its camelCase HTTP key; the verdict fields keep
 * their snake_case.
 */
export interface RebuildReport {
	allMatched: boolean;
	tables: TableVerdict[];
}

/**
 * One recent event in the active-session snapshot feed.
 */
export interface RecentEvent {
	type: NotableEventCategory;
	description: string;
	value: number;
	eventType: NotableEventType;
	timestamp: string | null;
	id: string;
}

/**
 * One activity's projection toward the recommender target.
 */
export interface RecommenderActivity {
	activity: string;
	professions: string[];
	pesToPlusOne: number | null;
	gainAtCap: number;
	series: number[];
	contributors: RecommenderContribution[];
}

/**
 * One skill's share of a recommended activity's projected gain.
 */
export interface RecommenderContribution {
	name: string;
	currentLevel: number;
	levelGain: number;
	targetGain: number;
}

/**
 * What the activity recommender optimises toward. A closed vocabulary:
 * the bindings expose only these two, so an out-of-vocabulary target is
 * unrepresentable rather than validated.
 */
export type RecommenderTargetKind = 'hp' | 'profession';

/**
 * The reject verb's result: `{ok: true}` on success, the lone `error`
 * on a refusal.
 */
export interface RejectResult {
	ok?: boolean | null;
	error?: string | null;
}

/**
 * The release-mob acknowledgement.
 */
export interface ReleaseResult {
	released: string | null;
}

/**
 * The one-shot repair-cost read (`exclude_unset`): the cost / raw text /
 * confidence on success, plus `error` on a logical refusal.
 */
export interface RepairScanResult {
	cost_ped?: number | null;
	raw_text?: string | null;
	confidence?: number | null;
	error?: string | null;
}

/**
 * The liquid + progression returns breakdown.
 */
export interface ReturnsBreakdown {
	lootTt: number;
	pes: number;
	codexPes: number;
	questPes: number;
	ledger: Record<string, number>;
}

/**
 * The settled scan phase, in the wire vocabulary the overlay switches on.
 */
export type ScanPhase = 'idle' | 'capturing' | 'processing' | 'awaiting_review';

/**
 * The per-page OCR progress counter.
 */
export interface ScanProgress {
	done: number;
	total: number;
}

/**
 * The full manual-scan status, in the response-model field order the
 * HTTP layer emitted. `error` carries a logical refusal's message (null
 * on success); every other field is always present.
 */
export interface ScanStatus {
	active: boolean;
	processing: boolean;
	captured_pages: number;
	expected_pages: number;
	last_scan_time: number | null;
	skills_count: number;
	configured: boolean;
	game_window_present: boolean;
	phase: ScanPhase;
	processing_progress: ScanProgress;
	has_pending_result: boolean;
	error: string | null;
}

/**
 * A catalogue vocabulary the search accepts; each maps to one snapshot
 * endpoint. An out-of-vocabulary value cannot be constructed (the
 * bindings expose the closed union), so the old unknown-type reply
 * class is unrepresentable rather than handled.
 */
export type SearchKind = 'weapon' | 'amp' | 'healer' | 'scope' | 'absorber' | 'consumable' | 'tool' | 'implant';

/**
 * The segment acknowledgement: the segment name now in force on the
 * running session (null: no segment open).
 */
export interface SegmentStateResult {
	segmentName: string | null;
}

/**
 * The session-config acknowledgement: the facet values now in force
 * (null: not declared).
 */
export interface SessionConfigResult {
	sessionName: string | null;
	skillBoostPercent: number | null;
}

/**
 * The full session detail.
 */
export interface SessionDetail {
	sessionId: string;
	summary: SessionSummary;
	harvest: HarvestSummary;
	/** The session-name facet as recorded. Present here because the record is where the name is corrected: the overlay fixes it once a session starts. */
	sessionName: string | null;
	mobEntryMode: MobEntryMode;
	notableEvents: NotableEvent[];
	lootBreakdown: LootEntry[];
	deactivatedLootBreakdown: LootEntry[];
	mobBreakdown: MobBreakdownRow[];
	effectiveLoot: number;
	toolStats: ToolStat[];
	skillGains: SkillGain[];
}

/**
 * The interval kinds as the engine writes them today. The schema keeps
 * the vocabulary open on purpose (a new kind must not need a
 * migration); the wire types the set that exists, and the reader skips
 * a row it cannot parse rather than failing the whole read.
 */
export type SessionIntervalKind = 'modifier' | 'segment' | 'quest' | 'consumable';

/**
 * One recorded interval of a session: its identity, bounds, and the
 * events attributed to it through the contexts stamped at insert.
 */
export interface SessionIntervalRow {
	id: number;
	kind: SessionIntervalKind;
	/** The display name (a segment's name, a quest's title); null for kinds that need none. */
	label: string | null;
	/** What the interval points at (a quest id); interpretation is implied by `kind`. */
	refId: number | null;
	/** The modifier magnitude, where 0 is the declared unboosted baseline and null means the kind carries none. */
	magnitude: number | null;
	/** Wall-clock bounds in epoch seconds, exactly as declared. Never compare these against event timestamps: events carry the chat log's centralised server time, an hour apart on real data, which is why attribution goes through contexts instead. */
	startedAt: number;
	/** Null while the interval is still open. */
	endedAt: number | null;
	/** Attributed event counts, by context membership. */
	kills: number;
	harvests: number;
	skillGains: number;
}

/**
 * A session's recorded intervals, oldest first.
 */
export interface SessionIntervals {
	sessionId: string;
	intervals: SessionIntervalRow[];
}

/**
 * A keyset page of session-list rows plus the opaque cursor for the
 * next page (`null` on the last page) and the whole-table session
 * count, mirroring the ledger's [`crate::analytics::LedgerPage`] shape.
 */
export interface SessionPage {
	sessions: TrackingSession[];
	nextCursor: string | null;
	total: number;
}

/**
 * The quest-link suggestion (all seven fields always present).
 */
export interface SessionQuestLinkSuggestion {
	sessionId: string;
	suggestionType: QuestLinkSuggestionType | null;
	reason: QuestLinkReason | null;
	questId: string | null;
	questName: string | null;
	playlistId: string | null;
	playlistName: string | null;
}

/**
 * The post-hoc session-rename result.
 */
export interface SessionRenameResult {
	sessionId: string;
	sessionName: string | null;
}

/**
 * The session-detail headline summary.
 */
export interface SessionSummary {
	cost: number;
	returns: number;
	pes: number;
	net: number;
	returnRate: number;
	kills: number;
	duration: number;
	costBreakdown: CostBreakdown;
}

/**
 * The partial settings update: every field optional, only the present
 * ones applied (the `exclude_unset` semantics the pydantic model had).
 * `active_trifecta_preset_id` is a double option so an explicit `null`
 * (clear the active preset) stays distinct from an absent field (leave
 * it untouched); every other field is nullless, so a plain `Option`
 * carries the present/absent distinction.
 */
export interface SettingsPatch {
	chatlog_path?: string | null;
	player_name?: string | null;
	hotbar_hooks_enabled?: boolean | null;
	repair_ocr_enabled?: boolean | null;
	end_of_session_armour_reminder_enabled?: boolean | null;
	developer_mode_enabled?: boolean | null;
	session_name?: string | null;
	/** Double-optioned so the patch can express all three states: absent leaves the declaration alone, an explicit null withdraws it, and a number (including 0) declares it. */
	declared_skill_boost_percent?: number | null;
	hotbar?: Record<string, unknown> | null;
	active_trifecta_preset_id?: string | null;
	trifecta_presets?: TrifectaPresetInput[] | null;
	harvest_guardrail?: HarvestGuardrailInput | null;
	loot_filter_blacklist?: string[] | null;
}

/**
 * One per-skill gain (attributes excluded).
 */
export interface SkillGain {
	skillName: string;
	level: number;
	ttValueGained: number;
}

/**
 * One calibrated skill row.
 */
export interface SkillLevel {
	name: string;
	category: string;
	level: number;
	anchorLevel: number | null;
	gainSinceAnchor: number | null;
	rankName: string;
	ttValue: number;
	isAttribute: boolean;
}

/**
 * The held OCR result awaiting review: canonical skill name to level.
 */
export interface SkillScanPending {
	skills: Record<string, number>;
}

/**
 * The spacebar-capture toggle acknowledgement: the resulting enabled
 * state after the flip.
 */
export interface SpacebarResult {
	ok: boolean;
	enabled: boolean;
}

/**
 * The start lifecycle acknowledgement.
 */
export interface StartResult {
	session_id: string;
	started_at: string;
	status: TrackingState;
}

/**
 * One of the top professions on the stats card: the trimmed shape the
 * card renders (name, level, category), not the full profession row.
 */
export interface StatProfession {
	name: string;
	level: number;
	category: string;
}

/**
 * A stock-conversion payload (recycling into Nanocubes at 1:1 TT).
 */
export interface StockConversionInput {
	sourceItem: string;
	targetItem: string;
	quantity: number;
	convertedAt?: string | null;
}

/**
 * One canonical item the player currently holds: recorded loot still in
 * hand after everything that has left through a listing or a conversion,
 * and back through an expiry. Position context only: it never feeds market
 * opportunity or its confidence levels, which stay holding-independent.
 */
export interface StockPosition {
	itemName: string;
	quantity: number;
	ttValue: number;
	/** Quantity sitting in an unresolved auction listing. Already out of `quantity`, since listed stock has left the player's inventory in game, but reported so it does not read as simply gone. */
	listedQuantity: number;
}

/**
 * The stop lifecycle acknowledgement.
 */
export interface StopResult {
	session_id: string;
	started_at: string;
	ended_at: string | null;
	kill_count: number;
}

/**
 * One projection table's verdict from a rebuild-and-verify run: the
 * table name, whether its rebuilt rows were byte-identical to the
 * incrementally-maintained ones, and the row count after the rebuild.
 */
export interface TableVerdict {
	table: string;
	matched: boolean;
	row_count: number;
}

/**
 * One day of the Overview timeline.
 */
export interface TimelineDay {
	date: string;
	lootTt: number;
	pes: number;
	codexPes: number;
	questPes: number;
	ledgerGains: Record<string, number>;
	trackingCost: number;
	ledgerLosses: Record<string, number>;
}

/**
 * The activity family the held tool implies the next action belongs
 * to: the overlay's derived-activity feedback ("this is Tree Cutting"
 * versus "this is Hunting"). Absent when no tool is known.
 */
export type ToolActivity = 'hunting' | 'treecutting';

/**
 * One per-tool aggregate.
 */
export interface ToolStat {
	weaponName: string;
	shotsFired: number;
	damageDealt: number;
	crits: number;
	costAttributed: number;
}

/**
 * One row of the session list.
 */
export interface TrackingSession {
	id: string;
	startTime: string | null;
	endTime: string | null;
	duration: number;
	primaryMobs: string[];
	primaryWeapons: string[];
	cost: number;
	returns: number;
	net: number;
	returnRate: number;
	globals: number;
	hofs: number;
}

/**
 * The consolidated dashboard hydration snapshot: the polymorphic idle /
 * active shape, in the model's declaration order. Every field is optional
 * and skipped when absent; under the ratified exclude-unset -> exclude-none
 * movement a present-null field is dropped rather than serialised null.
 */
export interface TrackingSnapshot {
	status?: TrackingState | null;
	hotbarListenerActive?: boolean | null;
	weaponAttribution?: WeaponAttribution | null;
	repairOcrEnabled?: boolean | null;
	endOfSessionArmourReminderEnabled?: boolean | null;
	/** The session-name facet: the active session's when tracking, the configured next-session value when idle. */
	sessionName?: string | null;
	/** The skill-boost facet (labelled percent), same idle/active sourcing as the session name. */
	skillBoostPercent?: number | null;
	/** The open segment's name. Active-only by nature: a segment exists exactly while its session runs, so the idle branch never carries the key and an active session without a segment drops it too. */
	segmentName?: string | null;
	currentMob?: string | null;
	currentTool?: string | null;
	/** What the held tool implies the next action is recorded as. */
	currentActivity?: ToolActivity | null;
	/** The open quest slices' names, newest first: the quest facet as the lifecycle auto-records it (several dailies can stack). Absent when no slice is open, so the readout never claims a quest that is not actually running. */
	questNames?: string[] | null;
	trifectaAttribution?: TrifectaAttribution | null;
	recentEvents?: RecentEvent[] | null;
	session_id?: string | null;
	started_at?: string | null;
	kill_count?: number | null;
	elapsed?: number | null;
	cost?: number | null;
	returns?: number | null;
	pes?: number | null;
	net?: number | null;
	returnRate?: number | null;
	damageDealtTotal?: number | null;
	weaponDamageDealt?: number | null;
	weaponCost?: number | null;
	shotsFiredTotal?: number | null;
	criticalHitsTotal?: number | null;
	maxDamage?: number | null;
	globalsCount?: number | null;
	hofsCount?: number | null;
	latestKillLoot?: number | null;
	multiplierLast?: number | null;
	multiplierAvg?: number | null;
	multiplierMax?: number | null;
	multiplierHistory?: number[] | null;
	cumulativeNetHistory?: number[] | null;
	/** Harvesting swings this session (successes plus explicit fails). */
	harvestSwings?: number | null;
	harvestSuccesses?: number | null;
	harvestLoot?: number | null;
	harvestCost?: number | null;
	/** The standing harvest-guardrail disagreement; present only while the loot evidence contradicts the hotbar-equipped tool. */
	harvestGuardrail?: HarvestGuardrailAlert | null;
	warnings?: Warning[] | null;
}

/**
 * The session state a tracking readout reports.
 */
export type TrackingState = 'idle' | 'active';

/**
 * The guardrail's closed board-yield vocabulary: the yield tier evidenced by
 * a swing's board output. The type name is the guardrail alias described on
 * `TreeSize` in the services layer.
 */
export type TreeSizeName = 'short' | 'long' | 'huge';

/**
 * The Overview headline trend, as the service computes it. The
 * serialised forms are byte-identical to the strings they replace.
 */
export type Trend = 'improving' | 'declining' | 'stable';

/**
 * The trifecta attribution summary (present when trifecta mode is active
 * and a preset or binding exists). Its members are always emitted (a
 * null binding stays on the wire), so none skip.
 */
export interface TrifectaAttribution {
	activePresetId: string | null;
	presetName: string | null;
	presets: TrifectaPresetRef[];
	smallWeapon: string | null;
	bigWeapon: string | null;
	healTool: string | null;
}

/**
 * One trifecta preset in a settings update. Field names stay in the
 * stored snake_case the config writer re-normalises.
 */
export interface TrifectaPresetInput {
	id: string;
	name: string;
	small_weapon_id?: number | null;
	big_weapon_id?: number | null;
	heal_id?: number | null;
}

/**
 * One preset reference inside the trifecta attribution summary.
 */
export interface TrifectaPresetRef {
	id: string;
	name: string;
}

/**
 * One trifecta preset in the settings view: the stored equipment ids
 * plus the live readiness validation against the library.
 */
export interface TrifectaPresetView {
	id: string;
	name: string;
	smallWeaponId: number | null;
	bigWeaponId: number | null;
	healId: number | null;
	ready: boolean;
	message: string | null;
}

/**
 * The trifecta block: every preset validated, with the active preset's
 * readiness lifted to the top level.
 */
export interface TrifectaSettings {
	activePresetId: string | null;
	activePresetName: string | null;
	presets: TrifectaPresetView[];
	ready: boolean;
	message: string | null;
}

/**
 * The undo verb's result: the status after the pop, plus the popped
 * page number. Absent on a refusal (the status carries the error).
 */
export interface UndoResult {
	active: boolean;
	processing: boolean;
	captured_pages: number;
	expected_pages: number;
	last_scan_time: number | null;
	skills_count: number;
	configured: boolean;
	game_window_present: boolean;
	phase: ScanPhase;
	processing_progress: ScanProgress;
	has_pending_result: boolean;
	error: string | null;
	undone_page?: number | null;
}

/**
 * One active-session warning.
 */
export interface Warning {
	type: NotableEventCategory;
	description: string;
	value: number;
}

/**
 * Which attribution source prices weapon shots.
 */
export type WeaponAttribution = 'hotbar' | 'trifecta';

export async function equipmentSearch(q: string, kind: SearchKind): Promise<EquipmentSearchHit[]> {
	return invokeCommand('equipment_search', { q, kind });
}

export async function equipmentLibrary(): Promise<EquipmentSummary[]> {
	return invokeCommand('equipment_library', {});
}

export async function equipmentAdd(req: EquipmentRequest): Promise<EquipmentSummary> {
	return invokeCommand('equipment_add', { req });
}

export async function equipmentUpdate(itemId: number, req: EquipmentRequest): Promise<EquipmentSummary> {
	return invokeCommand('equipment_update', { item_id: itemId, req });
}

export async function equipmentDelete(itemId: number): Promise<void> {
	return invokeCommand('equipment_delete', { item_id: itemId });
}

export async function equipmentDetail(itemId: number): Promise<EquipmentDetail> {
	return invokeCommand('equipment_detail', { item_id: itemId });
}

export async function characterCalibration(): Promise<CalibrationStatus> {
	return invokeCommand('character_calibration', {});
}

export async function characterStats(): Promise<ComputedCharacterStats> {
	return invokeCommand('character_stats', {});
}

export async function characterSkills(): Promise<SkillLevel[]> {
	return invokeCommand('character_skills', {});
}

export async function characterProfessions(): Promise<ProfessionLevel[]> {
	return invokeCommand('character_professions', {});
}

export async function characterProspectOptions(): Promise<CharacterProspectOptions> {
	return invokeCommand('character_prospect_options', {});
}

export async function characterProspect(query: ProspectQuery): Promise<ProspectResult> {
	return invokeCommand('character_prospect', { query });
}

export async function characterProfessionOptimizer(profession: string): Promise<ProfessionOptimizerResult> {
	return invokeCommand('character_profession_optimizer', { profession });
}

export async function characterPathOptimizer(profession: string, targetLevel: number | null, pedBudget: number | null): Promise<PathOptimizerResult> {
	return invokeCommand('character_path_optimizer', { profession, target_level: targetLevel, ped_budget: pedBudget });
}

export async function characterHpOptimizer(): Promise<HpOptimizerResult> {
	return invokeCommand('character_hp_optimizer', {});
}

export async function characterActivityRecommender(query: ActivityRecommenderQuery): Promise<ActivityRecommenderResult> {
	return invokeCommand('character_activity_recommender', { query });
}

export async function settingsGet(): Promise<AppSettings> {
	return invokeCommand('settings_get', {});
}

export async function settingsOverlayPosition(): Promise<OverlayPosition> {
	return invokeCommand('settings_overlay_position', {});
}

export async function settingsSetOverlayPosition(x: number, y: number): Promise<void> {
	return invokeCommand('settings_set_overlay_position', { x, y });
}

export async function settingsUpdate(patch: SettingsPatch): Promise<AppSettings> {
	return invokeCommand('settings_update', { patch });
}

export async function codexSpecies(): Promise<CodexSpecies[]> {
	return invokeCommand('codex_species', {});
}

export async function codexSpeciesRanks(speciesName: string): Promise<CodexSpeciesRanks> {
	return invokeCommand('codex_species_ranks', { species_name: speciesName });
}

export async function codexRecommend(speciesName: string, rank: number, professions: string[], target: CodexRecommendTarget): Promise<CodexSkillOption[]> {
	return invokeCommand('codex_recommend', { species_name: speciesName, rank, professions, target });
}

export async function codexMetaAttributes(): Promise<CodexMetaAttribute[]> {
	return invokeCommand('codex_meta_attributes', {});
}

export async function codexCalibrate(speciesName: string, rank: number): Promise<CodexCalibrateResult> {
	return invokeCommand('codex_calibrate', { species_name: speciesName, rank });
}

export async function codexClaim(speciesName: string, rank: number, skillName: string): Promise<CodexClaimResult> {
	return invokeCommand('codex_claim', { species_name: speciesName, rank, skill_name: skillName });
}

export async function codexUnclaim(speciesName: string): Promise<CodexClaimResult> {
	return invokeCommand('codex_unclaim', { species_name: speciesName });
}

export async function codexMetaClaim(attributeName: string): Promise<CodexMetaClaimResult> {
	return invokeCommand('codex_meta_claim', { attribute_name: attributeName });
}

export async function codexMasteryOptions(professions: string[], target: CodexRecommendTarget): Promise<CodexSkillOption[]> {
	return invokeCommand('codex_mastery_options', { professions, target });
}

export async function codexMasteryClaim(speciesName: string, skillName: string): Promise<CodexMasteryClaimResult> {
	return invokeCommand('codex_mastery_claim', { species_name: speciesName, skill_name: skillName });
}

export async function codexMasteryUnclaim(speciesName: string): Promise<CodexMasteryClaimResult> {
	return invokeCommand('codex_mastery_unclaim', { species_name: speciesName });
}

export async function questsList(): Promise<Quest[]> {
	return invokeCommand('quests_list', {});
}

export async function questGet(questId: number): Promise<Quest> {
	return invokeCommand('quest_get', { quest_id: questId });
}

export async function questCreate(input: QuestInput): Promise<Quest> {
	return invokeCommand('quest_create', { input });
}

export async function questUpdate(questId: number, input: QuestInput): Promise<Quest> {
	return invokeCommand('quest_update', { quest_id: questId, input });
}

export async function questDelete(questId: number): Promise<void> {
	return invokeCommand('quest_delete', { quest_id: questId });
}

export async function questStart(questId: number): Promise<Quest> {
	return invokeCommand('quest_start', { quest_id: questId });
}

export async function questComplete(questId: number): Promise<Quest> {
	return invokeCommand('quest_complete', { quest_id: questId });
}

export async function questCancel(questId: number, undoReward: boolean): Promise<Quest> {
	return invokeCommand('quest_cancel', { quest_id: questId, undo_reward: undoReward });
}

export async function questsMobs(): Promise<string[]> {
	return invokeCommand('quests_mobs', {});
}

export async function questsAnalytics(): Promise<QuestAnalyticsRow[]> {
	return invokeCommand('quests_analytics', {});
}

export async function playlistsList(): Promise<QuestPlaylist[]> {
	return invokeCommand('playlists_list', {});
}

export async function playlistCreate(input: PlaylistInput): Promise<QuestPlaylist> {
	return invokeCommand('playlist_create', { input });
}

export async function playlistUpdate(playlistId: number, input: PlaylistInput): Promise<QuestPlaylist> {
	return invokeCommand('playlist_update', { playlist_id: playlistId, input });
}

export async function playlistDelete(playlistId: number): Promise<void> {
	return invokeCommand('playlist_delete', { playlist_id: playlistId });
}

export async function playlistsAnalytics(): Promise<PlaylistAnalyticsRow[]> {
	return invokeCommand('playlists_analytics', {});
}

export async function analyticsOverview(period: string): Promise<AnalyticsOverview> {
	return invokeCommand('analytics_overview', { period });
}

export async function analyticsHunting(): Promise<AnalyticsHunting> {
	return invokeCommand('analytics_hunting', {});
}

export async function analyticsHarvest(period: string): Promise<AnalyticsHarvest> {
	return invokeCommand('analytics_harvest', { period });
}

export async function harvestStock(): Promise<StockPosition[]> {
	return invokeCommand('harvest_stock', {});
}

export async function harvestRealisedMarkup(): Promise<RealisedTierMarkup[]> {
	return invokeCommand('harvest_realised_markup', {});
}

export async function auctionListings(): Promise<AuctionListing[]> {
	return invokeCommand('auction_listings', {});
}

export async function auctionListingCreate(input: AuctionListingInput): Promise<AuctionListing> {
	return invokeCommand('auction_listing_create', { input });
}

export async function auctionListingConfirm(input: AuctionConfirmInput): Promise<AuctionListing> {
	return invokeCommand('auction_listing_confirm', { input });
}

export async function auctionListingExpire(input: AuctionExpireInput): Promise<AuctionListing> {
	return invokeCommand('auction_listing_expire', { input });
}

export async function stockConvert(input: StockConversionInput): Promise<void> {
	return invokeCommand('stock_convert', { input });
}

export async function activityHistory(): Promise<ActivityHistoryEntry[]> {
	return invokeCommand('activity_history', {});
}

export async function auctionSaleRevert(input: ActivityUndoInput): Promise<AuctionListing> {
	return invokeCommand('auction_sale_revert', { input });
}

export async function auctionListingUndo(input: ActivityUndoInput): Promise<void> {
	return invokeCommand('auction_listing_undo', { input });
}

export async function stockConversionUndo(input: ActivityUndoInput): Promise<void> {
	return invokeCommand('stock_conversion_undo', { input });
}

export async function ledgerList(cursor: string | null, limit: number | null): Promise<LedgerPage> {
	return invokeCommand('ledger_list', { cursor, limit });
}

export async function ledgerSummary(period: string): Promise<LedgerSummary> {
	return invokeCommand('ledger_summary', { period });
}

export async function ledgerCreate(entry: LedgerEntryInput): Promise<LedgerItem> {
	return invokeCommand('ledger_create', { entry });
}

export async function ledgerDelete(entryId: string): Promise<void> {
	return invokeCommand('ledger_delete', { entry_id: entryId });
}

export async function ledgerPresetsList(): Promise<LedgerPreset[]> {
	return invokeCommand('ledger_presets_list', {});
}

export async function ledgerPresetCreate(preset: LedgerPresetInput): Promise<LedgerPreset> {
	return invokeCommand('ledger_preset_create', { preset });
}

export async function ledgerPresetDelete(presetId: string): Promise<void> {
	return invokeCommand('ledger_preset_delete', { preset_id: presetId });
}

export async function inventoryList(): Promise<InventoryItem[]> {
	return invokeCommand('inventory_list', {});
}

export async function inventoryCreate(item: InventoryItemInput): Promise<InventoryItem> {
	return invokeCommand('inventory_create', { item });
}

export async function inventoryUpdate(itemId: string, patch: InventoryPatch): Promise<InventoryItem> {
	return invokeCommand('inventory_update', { item_id: itemId, patch });
}

export async function inventoryDelete(itemId: string): Promise<void> {
	return invokeCommand('inventory_delete', { item_id: itemId });
}

export async function inventorySell(itemId: string, sale: InventorySellInput): Promise<InventorySellResult> {
	return invokeCommand('inventory_sell', { item_id: itemId, sale });
}

export async function marketPastePreview(text: string): Promise<MarketPastePreview> {
	return invokeCommand('market_paste_preview', { text });
}

export async function marketPasteCommit(text: string): Promise<MarketCommitResult> {
	return invokeCommand('market_paste_commit', { text });
}

export async function marketOverview(): Promise<MarketOverviewRow[]> {
	return invokeCommand('market_overview', {});
}

export async function marketContributionBatch(): Promise<MarketContributionBatch | null> {
	return invokeCommand('market_contribution_batch', {});
}

export async function marketBreakEven(): Promise<MarketBreakEven> {
	return invokeCommand('market_break_even', {});
}

export async function marketMobRanking(horizon: MarketHorizon): Promise<MarketMobRankingRow[]> {
	return invokeCommand('market_mob_ranking', { horizon });
}

export async function marketHarvestMarkups(): Promise<MarketHarvestData> {
	return invokeCommand('market_harvest_markups', {});
}

export async function marketItemHistory(itemName: string, horizon: MarketHorizon): Promise<MarketHistoryPoint[]> {
	return invokeCommand('market_item_history', { item_name: itemName, horizon });
}

export async function scanStatus(): Promise<ScanStatus> {
	return invokeCommand('scan_status', {});
}

export async function scanStart(pageCount: number | null): Promise<ScanStatus> {
	return invokeCommand('scan_start', { page_count: pageCount });
}

export async function scanCapture(): Promise<CaptureResult> {
	return invokeCommand('scan_capture', {});
}

export async function scanCancel(): Promise<ScanStatus> {
	return invokeCommand('scan_cancel', {});
}

export async function scanUndo(): Promise<UndoResult> {
	return invokeCommand('scan_undo', {});
}

export async function scanProcess(): Promise<ScanStatus> {
	return invokeCommand('scan_process', {});
}

export async function scanAccept(): Promise<AcceptResult> {
	return invokeCommand('scan_accept', {});
}

export async function scanReject(): Promise<RejectResult> {
	return invokeCommand('scan_reject', {});
}

export async function scanPending(): Promise<SkillScanPending | null> {
	return invokeCommand('scan_pending', {});
}

export async function scanSpacebarCapture(enabled: boolean): Promise<SpacebarResult> {
	return invokeCommand('scan_spacebar_capture', { enabled });
}

export async function trackingSessions(cursor: string | null, limit: number | null): Promise<SessionPage> {
	return invokeCommand('tracking_sessions', { cursor, limit });
}

export async function trackingSessionDetail(sessionId: string): Promise<SessionDetail> {
	return invokeCommand('tracking_session_detail', { session_id: sessionId });
}

export async function trackingSessionIntervals(sessionId: string): Promise<SessionIntervals> {
	return invokeCommand('tracking_session_intervals', { session_id: sessionId });
}

export async function trackingSessionNameSuggestions(q: string, limit: number | null): Promise<string[]> {
	return invokeCommand('tracking_session_name_suggestions', { q, limit });
}

export async function trackingManualMobSuggestions(q: string, limit: number | null): Promise<ManualMobSuggestion[]> {
	return invokeCommand('tracking_manual_mob_suggestions', { q, limit });
}

export async function trackingSnapshot(): Promise<TrackingSnapshot> {
	return invokeCommand('tracking_snapshot', {});
}

export async function trackingQuestLinkSuggestion(sessionId: string): Promise<SessionQuestLinkSuggestion> {
	return invokeCommand('tracking_quest_link_suggestion', { session_id: sessionId });
}

export async function trackingStart(): Promise<StartResult> {
	return invokeCommand('tracking_start', {});
}

export async function trackingStop(): Promise<StopResult> {
	return invokeCommand('tracking_stop', {});
}

export async function trackingReleaseMob(): Promise<ReleaseResult> {
	return invokeCommand('tracking_release_mob', {});
}

export async function trackingManualMobLock(species: string, maturity: string | null): Promise<ManualMobLockResult> {
	return invokeCommand('tracking_manual_mob_lock', { species, maturity });
}

export async function trackingSessionConfig(sessionName: string | null, skillBoostPercent: number | null): Promise<SessionConfigResult> {
	return invokeCommand('tracking_session_config', { session_name: sessionName, skill_boost_percent: skillBoostPercent });
}

export async function trackingSegmentOpen(segmentName: string | null): Promise<SegmentStateResult> {
	return invokeCommand('tracking_segment_open', { segment_name: segmentName });
}

export async function trackingSegmentClose(): Promise<SegmentStateResult> {
	return invokeCommand('tracking_segment_close', {});
}

export async function trackingSegmentRename(segmentName: string): Promise<SegmentStateResult> {
	return invokeCommand('tracking_segment_rename', { segment_name: segmentName });
}

export async function trackingRenameSession(sessionId: string, sessionName: string | null): Promise<SessionRenameResult> {
	return invokeCommand('tracking_rename_session', { session_id: sessionId, session_name: sessionName });
}

export async function trackingRenameMob(sessionId: string, fromMobName: string, toMobName: string): Promise<MobEditResult> {
	return invokeCommand('tracking_rename_mob', { session_id: sessionId, from_mob_name: fromMobName, to_mob_name: toMobName });
}

export async function trackingRestoreMob(sessionId: string, currentMobName: string): Promise<MobEditResult> {
	return invokeCommand('tracking_restore_mob', { session_id: sessionId, current_mob_name: currentMobName });
}

export async function trackingLootItemActivate(sessionId: string, itemName: string): Promise<LootItemEditResult> {
	return invokeCommand('tracking_loot_item_activate', { session_id: sessionId, item_name: itemName });
}

export async function trackingLootItemDeactivate(sessionId: string, itemName: string): Promise<LootItemEditResult> {
	return invokeCommand('tracking_loot_item_deactivate', { session_id: sessionId, item_name: itemName });
}

export async function trackingArmourCost(sessionId: string, cost: number): Promise<ArmourCostResult> {
	return invokeCommand('tracking_armour_cost', { session_id: sessionId, cost });
}

export async function trackingRepairScan(sessionId: string): Promise<RepairScanResult> {
	return invokeCommand('tracking_repair_scan', { session_id: sessionId });
}

export async function trackingSessionDelete(sessionId: string): Promise<void> {
	return invokeCommand('tracking_session_delete', { session_id: sessionId });
}

export async function demoAnalyticsOverview(period: string): Promise<AnalyticsOverview> {
	return invokeCommand('demo_analytics_overview', { period });
}

export async function demoAnalyticsHunting(): Promise<AnalyticsHunting> {
	return invokeCommand('demo_analytics_hunting', {});
}

export async function demoAnalyticsHarvest(period: string): Promise<AnalyticsHarvest> {
	return invokeCommand('demo_analytics_harvest', { period });
}

export async function demoLedgerList(cursor: string | null, limit: number | null): Promise<LedgerPage> {
	return invokeCommand('demo_ledger_list', { cursor, limit });
}

export async function demoLedgerSummary(period: string): Promise<LedgerSummary> {
	return invokeCommand('demo_ledger_summary', { period });
}

export async function demoLedgerPresetsList(): Promise<LedgerPreset[]> {
	return invokeCommand('demo_ledger_presets_list', {});
}

export async function demoInventoryList(): Promise<InventoryItem[]> {
	return invokeCommand('demo_inventory_list', {});
}

export async function demoTrackingSessions(cursor: string | null, limit: number | null): Promise<SessionPage> {
	return invokeCommand('demo_tracking_sessions', { cursor, limit });
}

export async function demoTrackingSessionDetail(sessionId: string): Promise<SessionDetail> {
	return invokeCommand('demo_tracking_session_detail', { session_id: sessionId });
}

export async function demoTrackingSnapshot(): Promise<TrackingSnapshot> {
	return invokeCommand('demo_tracking_snapshot', {});
}

export async function devMetrics(): Promise<MetricsSnapshot> {
	return invokeCommand('dev_metrics', {});
}

export async function devCrashReporting(): Promise<CrashReportingStatus> {
	return invokeCommand('dev_crash_reporting', {});
}

export async function devSetCrashReporting(enabled: boolean): Promise<CrashReportingStatus> {
	return invokeCommand('dev_set_crash_reporting', { enabled });
}

export async function devCompactDatabase(): Promise<CompactResult> {
	return invokeCommand('dev_compact_database', {});
}

export async function devRebuildProjections(): Promise<RebuildReport> {
	return invokeCommand('dev_rebuild_projections', {});
}

export async function planetMapsList(): Promise<PlanetMap[]> {
	return invokeCommand('planet_maps_list', {});
}

export async function mapPinsList(planet: string, mapViewId: number | null): Promise<MapPin[]> {
	return invokeCommand('map_pins_list', { planet, map_view_id: mapViewId });
}

export async function mapPinsViewport(planet: string, mapViewId: number | null, lonMin: number, lonMax: number, latMin: number, latMax: number): Promise<MapPin[]> {
	return invokeCommand('map_pins_viewport', { planet, map_view_id: mapViewId, lon_min: lonMin, lon_max: lonMax, lat_min: latMin, lat_max: latMax });
}

export async function mapPinNearby(planet: string, mapViewId: number | null, lon: number, lat: number): Promise<NearbyMapPin | null> {
	return invokeCommand('map_pin_nearby', { planet, map_view_id: mapViewId, lon, lat });
}

export async function mapViewsList(planet: string): Promise<MapView[]> {
	return invokeCommand('map_views_list', { planet });
}

export async function mapViewCreate(planet: string, name: string): Promise<MapView> {
	return invokeCommand('map_view_create', { planet, name });
}

export async function mapViewRename(id: number, name: string): Promise<MapView> {
	return invokeCommand('map_view_rename', { id, name });
}

export async function mapViewDelete(id: number): Promise<void> {
	return invokeCommand('map_view_delete', { id });
}

export async function mapPinCreate(pin: MapPinInput): Promise<MapPin> {
	return invokeCommand('map_pin_create', { pin });
}

export async function mapPinUpdate(id: number, patch: MapPinPatch): Promise<MapPin> {
	return invokeCommand('map_pin_update', { id, patch });
}

export async function mapPinDelete(id: number): Promise<void> {
	return invokeCommand('map_pin_delete', { id });
}

export async function mapPinCooldown(id: number): Promise<MapPin> {
	return invokeCommand('map_pin_cooldown', { id });
}

export async function pinConfigsList(planet: string, mapViewId: number | null): Promise<PinConfig[]> {
	return invokeCommand('pin_configs_list', { planet, map_view_id: mapViewId });
}

export async function pinConfigCreate(input: PinConfigInput): Promise<PinConfig> {
	return invokeCommand('pin_config_create', { input });
}

export async function pinConfigUpdate(id: number, input: PinConfigEditInput): Promise<PinConfig> {
	return invokeCommand('pin_config_update', { id, input });
}

export async function pinConfigDelete(id: number): Promise<void> {
	return invokeCommand('pin_config_delete', { id });
}

export async function pinConfigReorder(ids: number[]): Promise<void> {
	return invokeCommand('pin_config_reorder', { ids });
}

export async function mapsCalibrationStart(): Promise<CoordCalibrationStatus> {
	return invokeCommand('maps_calibration_start', {});
}

export async function mapsCalibrationCancel(): Promise<CoordCalibrationStatus> {
	return invokeCommand('maps_calibration_cancel', {});
}

export async function mapsCalibrationStatus(): Promise<CoordCalibrationStatus> {
	return invokeCommand('maps_calibration_status', {});
}

export async function mapsScanCoordinates(planet: string | null): Promise<CoordScanResult> {
	return invokeCommand('maps_scan_coordinates', { planet });
}

export async function navigationSnapshot(): Promise<NavigationRun | null> {
	return invokeCommand('navigation_snapshot', {});
}

export async function navigationStart(planet: string, mapViewId: number | null, startLon: number, startLat: number, selectedPinIds: number[] | null, hotkey: string): Promise<NavigationRun> {
	return invokeCommand('navigation_start', { planet, map_view_id: mapViewId, start_lon: startLon, start_lat: startLat, selected_pin_ids: selectedPinIds, hotkey });
}

export async function navigationUpdatePosition(): Promise<NavigationPositionResult> {
	return invokeCommand('navigation_update_position', {});
}

export async function navigationMarkVisited(force: boolean): Promise<NavigationPositionResult> {
	return invokeCommand('navigation_mark_visited', { force });
}

export async function navigationSkip(): Promise<NavigationRun> {
	return invokeCommand('navigation_skip', {});
}

export async function navigationResolveHarvest(confirm: boolean): Promise<NavigationRun> {
	return invokeCommand('navigation_resolve_harvest', { confirm });
}

export async function navigationUndo(): Promise<NavigationRun> {
	return invokeCommand('navigation_undo', {});
}

export async function navigationEnd(): Promise<void> {
	return invokeCommand('navigation_end', {});
}

export async function radarCalibrationStart(): Promise<RadarCalibrationStatus> {
	return invokeCommand('radar_calibration_start', {});
}

export async function radarCalibrationCancel(): Promise<void> {
	return invokeCommand('radar_calibration_cancel', {});
}

export async function radarCalibrationStatus(): Promise<RadarCalibrationStatus> {
	return invokeCommand('radar_calibration_status', {});
}

export async function radarGeometry(): Promise<RadarGeometry | null> {
	return invokeCommand('radar_geometry', {});
}
