// Generated by `cargo xtask gen-ts` from the eo-api command manifest.
// Do not edit; regenerate after changing the Rust DTOs or manifest.
// CI holds this file in lock-step (`cargo xtask gen-ts --check`).

import { invokeCommand } from './invoke';

/** The serialised error every command rejects with. */
export type ApiErrorPayload = {
		message: string;
		kind: 'badRequest';
	} | {
		message: string;
		kind: 'notFound';
	} | {
		message: string;
		kind: 'conflict';
	} | {
		kind: 'internal';
	} | {
		kind: 'unavailable';
	};

/**
 * The absorber component of a stored weapon setup.
 */
export interface AbsorberComponent {
	catalogId?: string | null;
	name: string;
	decay: number;
	ammoBurn: number;
	absorptionPercent: number;
	markupPercent: number;
	isLimited: boolean;
}

/**
 * The full assembled settings response. Field order is the wire order
 * the frontend contract expects (and the HTTP body carried).
 */
export interface AppSettings {
	gameConnection: GameConnection;
	hotbarHooksEnabled: boolean;
	repairOcrEnabled: boolean;
	endOfSessionArmourReminderEnabled: boolean;
	developerModeEnabled: boolean;
	mobTrackingMode: string;
	mobTrackingTag: string;
	/** The slot-to-equipment map, carried through in its stored insertion order (`serde_json`'s `preserve_order`), so slot "0" stays last. */
	hotbar: {
	};
	trifecta: TrifectaSettings;
	lootFilterBlacklist: string[];
	dbPath: string;
	appVersion: string;
}

/**
 * GET calibration: whether skills are calibrated and how fresh.
 */
export interface CalibrationStatus {
	calibrated: boolean;
	lastCalibration?: string | null;
	stale: boolean;
}

/**
 * GET prospect-options: the grouped slice options, one list per axis.
 */
export interface CharacterProspectOptions {
	tags: ProspectOption[];
	mobs: ProspectOption[];
	weapons: ProspectOption[];
}

/**
 * The record a manual rank calibration returns.
 */
export interface CodexCalibrateResult {
	speciesName: string;
	rank: number;
}

/**
 * The record a rank claim (or its reversal) returns.
 */
export interface CodexClaimResult {
	speciesName: string;
	rank: number;
	skillName: string;
	pedValue: number;
}

/**
 * One meta attribute with its current calibrated level.
 */
export interface CodexMetaAttribute {
	name: string;
	currentLevel?: number | null;
}

/**
 * The record a meta claim returns.
 */
export interface CodexMetaClaimResult {
	attributeName: string;
	pedValue: number;
}

/**
 * One rank in a species' breakdown: the derived cost / reward / category
 * fields, plus the player's claim state for that rank. Field order is
 * the wire order (the breakdown's own fields, then the claim overlay).
 */
export interface CodexRank {
	rank: number;
	category: string;
	cost: number;
	rewardPed: number;
	cat4Bonus: boolean;
	cat4RewardPed?: number | null;
	skills: string[];
	cat4Skills: string[];
	claimed: boolean;
	claimedSkill?: string | null;
	claimedPed?: number | null;
	isNext: boolean;
}

/**
 * What a codex recommendation ranks by. A closed vocabulary: the
 * bindings expose only these two, so the HTTP route's out-of-vocabulary
 * 422 (it defaulted an unknown `target` to `profession`) is
 * unrepresentable rather than validated.
 */
export type CodexRecommendTarget = 'profession' | 'hp';

/**
 * One skill option in a rank recommendation: the reward it grants, the
 * levels that buys at the current point on the curve, and the profession
 * / HP contribution used to rank the list.
 */
export interface CodexSkillOption {
	skillName: string;
	category: string;
	rewardPed: number;
	currentLevel?: number | null;
	levelsGained: number;
	professionWeight: number;
	profContribution: number;
	hpIncrease?: number | null;
	hpGain: number;
	recommendRank?: number | null;
}

/**
 * One species in the codex listing: its base cost, the player's current
 * rank, and the next rank's derived category and cost (all `null` once
 * rank 25 is reached).
 */
export interface CodexSpecies {
	name: string;
	baseCost: number;
	codexType?: string | null;
	currentRank: number;
	nextRank?: number | null;
	nextCategory?: string | null;
	nextCost?: number | null;
}

/**
 * A species' full 25-rank breakdown, cross-referenced with the player's
 * claims and current rank.
 */
export interface CodexSpeciesRanks {
	speciesName: string;
	baseCost: number;
	codexType?: string | null;
	currentRank: number;
	ranks: CodexRank[];
}

/**
 * GET stats: current HP and the top five professions.
 */
export interface ComputedCharacterStats {
	hp: number;
	topProfessions: StatProfession[];
}

/**
 * One line of a cost breakdown.
 */
export interface CostBreakdownLine {
	component: string;
	costPec: number;
	markupMultiplier: number;
	effectiveCostPec: number;
}

/**
 * One configured component of a stored weapon setup.
 */
export interface EquipmentComponent {
	catalogId?: string | null;
	name: string;
	decay: number;
	ammoBurn: number;
	markupPercent: number;
	isLimited: boolean;
	damageEnhancers: number;
}

/**
 * The expanded library-entry detail.
 */
export interface EquipmentDetail {
	id: string;
	weapon: EquipmentComponent;
	amplifier?: EquipmentComponent | null;
	scope?: EquipmentComponent | null;
	absorber?: AbsorberComponent | null;
	costBreakdown: CostBreakdownLine[];
	totalCostPerUse: number;
}

/**
 * The stored equipment classes.
 */
export type EquipmentKind = 'weapon' | 'healing' | 'consumable';

/**
 * An add or update request. Field names stay in the request casing the
 * frontend has always sent.
 */
export interface EquipmentRequest {
	type: EquipmentKind;
	catalog_id?: string | null;
	name?: string | null;
	amp_catalog_id?: string | null;
	scope_catalog_id?: string | null;
	absorber_catalog_id?: string | null;
	weapon_markup?: number;
	amp_markup?: number;
	scope_markup?: number;
	absorber_markup?: number;
	damage_enhancers?: number;
}

/**
 * A catalogue search hit.
 */
export interface EquipmentSearchHit {
	catalogId?: string | null;
	name: string;
	/** Decay per use, PEC. */
	decay: number;
	/** Ammo burn per use, PEC (catalogue units / 100). */
	ammoBurn: number;
	isLimited: boolean;
}

/**
 * A library entry in the list shape.
 */
export interface EquipmentSummary {
	id: string;
	name: string;
	type: EquipmentKind;
	amplifierName?: string | null;
	costPerUse: number;
	damageMin?: number | null;
	damageMax?: number | null;
	reloadSeconds?: number | null;
	isLimited: boolean;
	/** 1 = base item, 2 = amplified, 3 = fully accessorised. */
	enrichmentLevel: number;
}

/**
 * A skill the path optimizer left out, with the reason.
 */
export interface ExcludedSkill {
	name: string;
	weight: number;
	reason: string;
}

/**
 * The game-connection block: the configured chat-log path, whether it
 * currently resolves to a file, and the player name.
 */
export interface GameConnection {
	chatLogPath: string;
	chatLogValid: boolean;
	playerName: string;
}

/**
 * One attribute row of the HP optimizer.
 */
export interface HpOptimizerAttribute {
	name: string;
	hpIncrease: number;
	currentLevel: number;
	levelsPerHp: number;
}

/**
 * GET hp-optimizer: the HP-per-PED breakdown across contributing
 * skills and attributes.
 */
export interface HpOptimizerResult {
	currentHp: number;
	skills: HpOptimizerSkill[];
	attributes: HpOptimizerAttribute[];
}

/**
 * One skill row of the HP optimizer.
 */
export interface HpOptimizerSkill {
	name: string;
	hpIncrease: number;
	currentLevel: number;
	levelsPerHp: number;
	pedPerHp: number;
	hpPerPed: number;
	codexCategory?: string | null;
	codexDivisor?: number | null;
}

/**
 * One attribute row of the profession / path optimizer.
 */
export interface OptimizerAttribute {
	name: string;
	weight: number;
	currentLevel: number;
	contributionFactor: number;
}

/**
 * One skill row of the profession optimizer.
 */
export interface OptimizerSkill {
	name: string;
	weight: number;
	currentLevel: number;
	levelsNeeded: number;
	pedToNextLevel: number;
	codexCategory?: string | null;
	codexDivisor?: number | null;
}

/**
 * GET overlay-position: the persisted overlay window coordinates (null
 * until first placed).
 */
export interface OverlayPosition {
	x?: number | null;
	y?: number | null;
}

/**
 * One allocation of the path optimizer.
 */
export interface PathAllocation {
	name: string;
	weight: number;
	currentLevel: number;
	levelsToGain: number;
	pedCost: number;
	newLevel: number;
	codexCategory?: string | null;
	codexDivisor?: number | null;
}

/**
 * GET profession-path-optimizer: the greedy allocation for a target
 * level or a PED budget. `inputTargetLevel` / `inputPedBudget` echo the
 * mode (exactly one is non-null); `error` marks a missing profession.
 */
export interface PathOptimizerResult {
	allocations: PathAllocation[];
	attributes: OptimizerAttribute[];
	profession: string;
	mode: string;
	inputTargetLevel?: number | null;
	inputPedBudget?: number | null;
	currentLevel: number;
	endLevel: number;
	professionLevelsGained: number;
	totalPed: number;
	excluded: ExcludedSkill[];
	error?: string | null;
}

/**
 * Per-playlist analytics in the wire shape
 * (`_format_playlist_analytics`).
 */
export interface PlaylistAnalyticsRow {
	playlistId: string;
	playlistName: string;
	questCount: number;
	longHorizonQuestCount: number;
	matchedSessions: number;
	totalRewardPed: number;
	totalImmediateRewardPed: number;
	totalBonusRewardPed: number;
	totalPesReward: number;
	totalImmediatePesReward: number;
	totalBonusPesReward: number;
	totalExpectedRewardPed: number;
	totalExpectedImmediateRewardPed: number;
	totalExpectedBonusRewardPed: number;
	totalDurationSec: number;
	totalWeaponCost: number;
	totalHealCost: number;
	totalEnhancerCost: number;
	totalArmourCost: number;
	totalLootTt: number;
	totalPes: number;
}

/**
 * A playlist create or update payload, in the frontend's snake_case
 * casing. The sole client sends `name` / `planet` / `estimated_minutes`
 * / `items` for both operations (never `quest_ids`); the service derives
 * membership from `items` whenever it is present, so the facade sends
 * exactly those keys and omits the vestigial `quest_ids`.
 */
export interface PlaylistInput {
	name: string;
	planet?: string;
	estimated_minutes?: number;
	items?: PlaylistItemInput[];
}

/**
 * One classified slot in a playlist's wire shape.
 */
export interface PlaylistItem {
	questId: string;
	description?: string | null;
	groupType: string;
}

/**
 * One classified quest slot in a playlist create/update.
 */
export interface PlaylistItemInput {
	quest_id: number;
	description?: string | null;
	group_type?: string;
}

/**
 * One profession row.
 */
export interface ProfessionLevel {
	name: string;
	level: number;
	anchorLevel?: number | null;
	gainSinceAnchor?: number | null;
	category: string;
}

/**
 * GET profession-optimizer: the cheapest-skill breakdown to the next
 * profession level. On a missing profession the declared tail fields
 * stay unset and only `error` accompanies the empty lists.
 */
export interface ProfessionOptimizerResult {
	skills: OptimizerSkill[];
	attributes: OptimizerAttribute[];
	profession?: string | null;
	currentLevel?: number | null;
	nextLevel?: number | null;
	gap?: number | null;
	error?: string | null;
}

/**
 * One grouped Prospect slice option.
 */
export interface ProspectOption {
	value: string;
	label: string;
	sessions: number;
	kills: number;
	hours: number;
	cycledPed: number;
}

/**
 * The Prospect forecast query. `sliceValue` is required for every slice
 * but `global`; `markupUplift` defaults to zero.
 */
export interface ProspectQuery {
	profession: string;
	targetLevel: number;
	sliceType: ProspectSliceType;
	sliceValue?: string | null;
	markupUplift?: number;
}

/**
 * GET prospect: the forecast. `error` is present only on the soft-error
 * paths (the frontend renders it inline rather than throwing); every
 * other field is always present, so the declared order below is the
 * wire order.
 */
export interface ProspectResult {
	error?: string | null;
	rows: ProspectRow[];
	warnings: string[];
	profession: string;
	sliceType: string;
	sliceValue?: string | null;
	markupUplift: number;
	currentLevel: number;
	targetLevel: number;
	projectedCycledPed: number;
	projectedHours: number;
	expectedLootTt: number;
	expectedNetTtBurn: number;
	speculativeLootTt?: number | null;
	speculativeNetTtBurn?: number | null;
	sample: ProspectSample;
}

/**
 * One skill/attribute row of a Prospect forecast.
 */
export interface ProspectRow {
	name: string;
	isAttribute: boolean;
	weight: number;
	currentLevel: number;
	observedShare: number;
	observedRate: number;
	projectedGain: number;
	projectedEndLevel: number;
	professionContribution: number;
	relevant: boolean;
}

/**
 * The observed sample a Prospect forecast projects from. The internal
 * `skillShares` / `attributeRates` maps are computed but not surfaced
 * (no consumer reads them; dropped with the migration).
 */
export interface ProspectSample {
	sessions: number;
	kills: number;
	hours: number;
	cycledPed: number;
	lootTt: number;
	pes: number;
	attributeLevels: number;
	cycledPerHour: number;
	lootPerHour: number;
	returnRate: number;
	pesPerPed: number;
	lootTtPerPed: number;
}

/**
 * The slice a Prospect forecast aggregates over. A closed vocabulary:
 * the bindings expose only these four, so the old out-of-vocabulary 422
 * is unrepresentable rather than validated.
 */
export type ProspectSliceType = 'global' | 'tag' | 'mob' | 'weapon';

/**
 * A quest in the wire shape (`_format_quest` key for key). Ids are
 * stringified; `rewardDescription` / `notes` collapse null-or-empty to
 * `""`; `rewardIsSkill` is the boolean of the stored int flag.
 */
export interface Quest {
	id: string;
	name: string;
	category?: string | null;
	targetMobs: string[];
	planet: string;
	waypoint?: string | null;
	cooldownDurationHours?: number | null;
	cooldownExpiresAt?: string | null;
	reward?: number | null;
	rewardIsSkill: boolean;
	expectedRewardMarkupPercent?: number | null;
	rewardDescription: string;
	notes: string;
	chainName?: string | null;
	chainPosition?: number | null;
	chainTotal?: number | null;
	playlistIds: string[];
	/** A fractional epoch-seconds timestamp (the tracker's clock is sub-second), null while the quest is not in progress. */
	startedAt?: number | null;
}

/**
 * Per-quest analytics in the wire shape (`_format_quest_analytics`).
 * The reward and cost columns are model-float coerced and rounded; the
 * session count is an integer; the markup passes through raw.
 */
export interface QuestAnalyticsRow {
	questId: string;
	questName: string;
	planet: string;
	category?: string | null;
	rewardPed: number;
	rewardIsSkill: boolean;
	expectedRewardMarkupPercent?: number | null;
	totalExpectedRewardPed: number;
	linkedSessions: number;
	totalDurationSec: number;
	totalWeaponCost: number;
	totalHealCost: number;
	totalEnhancerCost: number;
	totalArmourCost: number;
	totalLootTt: number;
	totalPes: number;
}

/**
 * A quest create or update payload. One DTO serves both operations, in
 * the frontend's snake_case field casing: the sole client sends the
 * full field set for both create and update (nulls explicit), so every
 * field is serialised to the service `Value` (present-null clears a
 * column on update, exactly as the exclude-unset contract did for the
 * only payload the client ever produced). `update_quest` ignores the
 * `mobs` key by design, so a full payload is behaviour-identical to the
 * HTTP path either way.
 */
export interface QuestInput {
	name: string;
	planet?: string;
	category?: string | null;
	waypoint?: string | null;
	cooldown_hours?: number | null;
	reward_ped?: number | null;
	reward_is_skill?: boolean;
	expected_reward_markup_percent?: number | null;
	reward_description?: string | null;
	notes?: string | null;
	chain_name?: string | null;
	chain_position?: number | null;
	chain_total?: number | null;
	mobs?: string[];
}

/**
 * A playlist in the wire shape (`_format_playlist`). Membership arrives
 * pre-classified from the service; ids are stringified.
 */
export interface QuestPlaylist {
	id: string;
	name: string;
	planet: string;
	estimatedMinutes: number;
	questIds: string[];
	immediateQuestIds: string[];
	longHorizonQuestIds: string[];
	items: PlaylistItem[];
}

/**
 * A catalogue vocabulary the search accepts; each maps to one snapshot
 * endpoint. An out-of-vocabulary value cannot be constructed (the
 * bindings expose the closed union), so the old unknown-type reply
 * class is unrepresentable rather than handled.
 */
export type SearchKind = 'weapon' | 'amp' | 'healer' | 'scope' | 'absorber' | 'consumable';

/**
 * The partial settings update: every field optional, only the present
 * ones applied (the `exclude_unset` semantics the pydantic model had).
 * `active_trifecta_preset_id` is a double option so an explicit `null`
 * (clear the active preset) stays distinct from an absent field (leave
 * it untouched); every other field is nullless, so a plain `Option`
 * carries the present/absent distinction.
 */
export interface SettingsPatch {
	chatlog_path?: string | null;
	player_name?: string | null;
	hotbar_hooks_enabled?: boolean | null;
	repair_ocr_enabled?: boolean | null;
	end_of_session_armour_reminder_enabled?: boolean | null;
	developer_mode_enabled?: boolean | null;
	mob_tracking_mode?: string | null;
	mob_tracking_tag?: string | null;
	hotbar?: {
	} | null;
	active_trifecta_preset_id?: string | null;
	trifecta_presets?: TrifectaPresetInput[] | null;
	loot_filter_blacklist?: string[] | null;
}

/**
 * One calibrated skill row.
 */
export interface SkillLevel {
	name: string;
	category: string;
	level: number;
	anchorLevel?: number | null;
	gainSinceAnchor?: number | null;
	rankName: string;
	ttValue: number;
	isAttribute: boolean;
}

/**
 * One of the top professions on the stats card: the trimmed shape the
 * card renders (name, level, category), not the full profession row.
 */
export interface StatProfession {
	name: string;
	level: number;
	category: string;
}

/**
 * One trifecta preset in a settings update. Field names stay in the
 * stored snake_case the config writer re-normalises.
 */
export interface TrifectaPresetInput {
	id: string;
	name: string;
	small_weapon_id?: number | null;
	big_weapon_id?: number | null;
	heal_id?: number | null;
}

/**
 * One trifecta preset in the settings view: the stored equipment ids
 * plus the live readiness validation against the library.
 */
export interface TrifectaPresetView {
	id: string;
	name: string;
	smallWeaponId?: number | null;
	bigWeaponId?: number | null;
	healId?: number | null;
	ready: boolean;
	message?: string | null;
}

/**
 * The trifecta block: every preset validated, with the active preset's
 * readiness lifted to the top level.
 */
export interface TrifectaSettings {
	activePresetId?: string | null;
	activePresetName?: string | null;
	presets: TrifectaPresetView[];
	ready: boolean;
	message?: string | null;
}

export async function equipmentSearch(q: string, kind: SearchKind): Promise<EquipmentSearchHit[]> {
	return invokeCommand('equipment_search', { q, kind });
}

export async function equipmentLibrary(): Promise<EquipmentSummary[]> {
	return invokeCommand('equipment_library', {});
}

export async function equipmentAdd(req: EquipmentRequest): Promise<EquipmentSummary> {
	return invokeCommand('equipment_add', { req });
}

export async function equipmentUpdate(itemId: number, req: EquipmentRequest): Promise<EquipmentSummary> {
	return invokeCommand('equipment_update', { item_id: itemId, req });
}

export async function equipmentDelete(itemId: number): Promise<void> {
	return invokeCommand('equipment_delete', { item_id: itemId });
}

export async function equipmentDetail(itemId: number): Promise<EquipmentDetail> {
	return invokeCommand('equipment_detail', { item_id: itemId });
}

export async function characterCalibration(): Promise<CalibrationStatus> {
	return invokeCommand('character_calibration', {});
}

export async function characterStats(): Promise<ComputedCharacterStats> {
	return invokeCommand('character_stats', {});
}

export async function characterSkills(): Promise<SkillLevel[]> {
	return invokeCommand('character_skills', {});
}

export async function characterProfessions(): Promise<ProfessionLevel[]> {
	return invokeCommand('character_professions', {});
}

export async function characterProspectOptions(): Promise<CharacterProspectOptions> {
	return invokeCommand('character_prospect_options', {});
}

export async function characterProspect(query: ProspectQuery): Promise<ProspectResult> {
	return invokeCommand('character_prospect', { query });
}

export async function characterProfessionOptimizer(profession: string): Promise<ProfessionOptimizerResult> {
	return invokeCommand('character_profession_optimizer', { profession });
}

export async function characterPathOptimizer(profession: string, targetLevel: number | null, pedBudget: number | null): Promise<PathOptimizerResult> {
	return invokeCommand('character_path_optimizer', { profession, target_level: targetLevel, ped_budget: pedBudget });
}

export async function characterHpOptimizer(): Promise<HpOptimizerResult> {
	return invokeCommand('character_hp_optimizer', {});
}

export async function settingsGet(): Promise<AppSettings> {
	return invokeCommand('settings_get', {});
}

export async function settingsOverlayPosition(): Promise<OverlayPosition> {
	return invokeCommand('settings_overlay_position', {});
}

export async function settingsSetOverlayPosition(x: number, y: number): Promise<void> {
	return invokeCommand('settings_set_overlay_position', { x, y });
}

export async function settingsUpdate(patch: SettingsPatch): Promise<AppSettings> {
	return invokeCommand('settings_update', { patch });
}

export async function codexSpecies(): Promise<CodexSpecies[]> {
	return invokeCommand('codex_species', {});
}

export async function codexSpeciesRanks(speciesName: string): Promise<CodexSpeciesRanks> {
	return invokeCommand('codex_species_ranks', { species_name: speciesName });
}

export async function codexRecommend(speciesName: string, rank: number, profession: string | null, target: CodexRecommendTarget): Promise<CodexSkillOption[]> {
	return invokeCommand('codex_recommend', { species_name: speciesName, rank, profession, target });
}

export async function codexMetaAttributes(): Promise<CodexMetaAttribute[]> {
	return invokeCommand('codex_meta_attributes', {});
}

export async function codexCalibrate(speciesName: string, rank: number): Promise<CodexCalibrateResult> {
	return invokeCommand('codex_calibrate', { species_name: speciesName, rank });
}

export async function codexClaim(speciesName: string, rank: number, skillName: string): Promise<CodexClaimResult> {
	return invokeCommand('codex_claim', { species_name: speciesName, rank, skill_name: skillName });
}

export async function codexUnclaim(speciesName: string): Promise<CodexClaimResult> {
	return invokeCommand('codex_unclaim', { species_name: speciesName });
}

export async function codexMetaClaim(attributeName: string): Promise<CodexMetaClaimResult> {
	return invokeCommand('codex_meta_claim', { attribute_name: attributeName });
}

export async function questsList(): Promise<Quest[]> {
	return invokeCommand('quests_list', {});
}

export async function questGet(questId: number): Promise<Quest> {
	return invokeCommand('quest_get', { quest_id: questId });
}

export async function questCreate(input: QuestInput): Promise<Quest> {
	return invokeCommand('quest_create', { input });
}

export async function questUpdate(questId: number, input: QuestInput): Promise<Quest> {
	return invokeCommand('quest_update', { quest_id: questId, input });
}

export async function questDelete(questId: number): Promise<void> {
	return invokeCommand('quest_delete', { quest_id: questId });
}

export async function questStart(questId: number): Promise<Quest> {
	return invokeCommand('quest_start', { quest_id: questId });
}

export async function questComplete(questId: number): Promise<Quest> {
	return invokeCommand('quest_complete', { quest_id: questId });
}

export async function questCancel(questId: number, undoReward: boolean): Promise<Quest> {
	return invokeCommand('quest_cancel', { quest_id: questId, undo_reward: undoReward });
}

export async function questsMobs(): Promise<string[]> {
	return invokeCommand('quests_mobs', {});
}

export async function questsAnalytics(): Promise<QuestAnalyticsRow[]> {
	return invokeCommand('quests_analytics', {});
}

export async function playlistsList(): Promise<QuestPlaylist[]> {
	return invokeCommand('playlists_list', {});
}

export async function playlistCreate(input: PlaylistInput): Promise<QuestPlaylist> {
	return invokeCommand('playlist_create', { input });
}

export async function playlistUpdate(playlistId: number, input: PlaylistInput): Promise<QuestPlaylist> {
	return invokeCommand('playlist_update', { playlist_id: playlistId, input });
}

export async function playlistDelete(playlistId: number): Promise<void> {
	return invokeCommand('playlist_delete', { playlist_id: playlistId });
}

export async function playlistsAnalytics(): Promise<PlaylistAnalyticsRow[]> {
	return invokeCommand('playlists_analytics', {});
}
