/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/demo/analytics/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Analytics Activity */
        get: operations["demo_analytics_activity_api_demo_analytics_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Inventory Items */
        get: operations["demo_list_inventory_items_api_demo_analytics_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Ledger */
        get: operations["demo_list_ledger_api_demo_analytics_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/ledger/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Ledger Presets */
        get: operations["demo_list_ledger_presets_api_demo_analytics_ledger_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Analytics Overview */
        get: operations["demo_analytics_overview_api_demo_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/tracking/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Get Session */
        get: operations["demo_get_session_api_demo_tracking_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/tracking/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Sessions */
        get: operations["demo_list_sessions_api_demo_tracking_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/tracking/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Tracking Snapshot */
        get: operations["demo_tracking_snapshot_api_demo_tracking_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a tracking session and all associated data.
         */
        delete: operations["delete_session_api_tracking_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsActivity
         * @description The activity tab's mob / tag / weapon comparison tables.
         */
        AnalyticsActivity: {
            /** Mobcomparisons */
            mobComparisons: components["schemas"]["MobComparison"][];
            /** Tagcomparisons */
            tagComparisons: components["schemas"]["TagComparison"][];
            /** Weaponcomparisons */
            weaponComparisons: components["schemas"]["WeaponComparison"][];
        } & {
            [key: string]: unknown;
        };
        /** AnalyticsOverview */
        AnalyticsOverview: {
            lossesBreakdown: components["schemas"]["LossesBreakdown"];
            /** Monthlybreakdown */
            monthlyBreakdown: components["schemas"]["MonthlyPoint"][];
            returnsBreakdown: components["schemas"]["ReturnsBreakdown"];
            /** Timeline */
            timeline: components["schemas"]["TimelinePoint"][];
            /** Totalgains */
            totalGains: number;
            /** Totallosses */
            totalLosses: number;
            /** Totalreturnrate */
            totalReturnRate: number;
            /** Trend */
            trend: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description The health-check acknowledgement.
         */
        HealthStatus: {
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InventoryItemModel
         * @description A persistent-inventory ledger item.
         */
        InventoryItemModel: {
            /** Acquiredat */
            acquiredAt: string;
            /** Id */
            id: string;
            /** Markuppaid */
            markupPaid: number;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Ttvalue */
            ttValue: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * LedgerItem
         * @description A liquid-economy ledger entry (expense or markup).
         */
        LedgerItem: {
            /** Amount */
            amount: number;
            /** Date */
            date: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Tag */
            tag: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * LedgerPresetItem
         * @description A ledger quick-entry preset (distinct from a ledger entry: name, not date).
         */
        LedgerPresetItem: {
            /** Amount */
            amount: number;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tag */
            tag: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * LootItem
         * @description An item-name aggregate loot row within a session detail.
         */
        LootItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Ttvalue */
            ttValue: number;
        } & {
            [key: string]: unknown;
        };
        /** LossesBreakdown */
        LossesBreakdown: {
            /** Cycledbreakdown */
            cycledBreakdown: unknown;
            /** Ledger */
            ledger: {
                [key: string]: number;
            };
            /** Trackingcost */
            trackingCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * MobBreakdownRow
         * @description A per-mob row for the session metadata-edit affordance.
         */
        MobBreakdownRow: {
            /** Currentname */
            currentName: string;
            /** Killcount */
            killCount: number;
            /** Originalname */
            originalName?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MobComparison
         * @description A per-mob activity comparison row.
         */
        MobComparison: {
            /** Cycled */
            cycled: number;
            /** Hours */
            hours: number;
            /** Kills */
            kills: number;
            /** Lootrate */
            lootRate: number;
            /** Mobname */
            mobName: string;
            /** Pesper100Ped */
            pesPer100Ped: number;
            /** Sessions */
            sessions: number;
        } & {
            [key: string]: unknown;
        };
        /** MonthlyPoint */
        MonthlyPoint: {
            /** Codexpes */
            codexPes: number;
            /** Ledgergains */
            ledgerGains: {
                [key: string]: unknown;
            };
            /** Ledgerlosses */
            ledgerLosses: {
                [key: string]: unknown;
            };
            /** Loottt */
            lootTt: number;
            /** Month */
            month: string;
            /** Pes */
            pes: number;
            /** Questpes */
            questPes: number;
            /** Trackingcost */
            trackingCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * NotableEvent
         * @description A dashboard activity-feed entry.
         *
         *     Covers both the notable-event payload (global/HoF/quest) and the tracker
         *     warning entry, which share ``type``/``description``/``value`` and differ in
         *     the optional ``eventType``/``timestamp``/``id`` keys.
         */
        NotableEvent: {
            /** Description */
            description: string;
            /** Eventtype */
            eventType?: string | null;
            /** Id */
            id?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Type */
            type: string;
            /** Value */
            value: number;
        } & {
            [key: string]: unknown;
        };
        /** ReturnsBreakdown */
        ReturnsBreakdown: {
            /** Codexpes */
            codexPes: number;
            /** Ledger */
            ledger: {
                [key: string]: number;
            };
            /** Loottt */
            lootTt: number;
            /** Pes */
            pes: number;
            /** Questpes */
            questPes: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionDeletedResult
         * @description Acknowledgement that a session was deleted (2-key).
         */
        SessionDeletedResult: {
            /** Sessionid */
            sessionId: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionDetail
         * @description The expanded detail for a session.
         */
        SessionDetail: {
            /** Deactivatedlootbreakdown */
            deactivatedLootBreakdown: components["schemas"]["LootItem"][];
            /** Effectiveloot */
            effectiveLoot: number;
            /** Lootbreakdown */
            lootBreakdown: components["schemas"]["LootItem"][];
            /** Mobbreakdown */
            mobBreakdown: components["schemas"]["MobBreakdownRow"][];
            /** Mobentrymode */
            mobEntryMode: string;
            /** Notableevents */
            notableEvents: components["schemas"]["SessionNotableEvent"][];
            /** Sessionid */
            sessionId: string;
            /** Skillgains */
            skillGains: components["schemas"]["SessionSkillGain"][];
            summary: components["schemas"]["SessionSummary"];
            /** Toolstats */
            toolStats: components["schemas"]["ToolStat"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionNotableEvent
         * @description A notable event within a session detail (target/item shape).
         */
        SessionNotableEvent: {
            /** Eventtype */
            eventType: string;
            /** Item */
            item: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Value */
            value: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionSkillGain
         * @description A per-skill gain within a session detail.
         */
        SessionSkillGain: {
            /** Level */
            level: number;
            /** Skillname */
            skillName: string;
            /** Ttvaluegained */
            ttValueGained: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionSummary
         * @description The headline summary of a session detail.
         */
        SessionSummary: {
            /** Cost */
            cost: number;
            costBreakdown: components["schemas"]["TrackingCostBreakdown"];
            /** Duration */
            duration: number;
            /** Kills */
            kills: number;
            /** Net */
            net: number;
            /** Pes */
            pes: number;
            /** Returnrate */
            returnRate: number;
            /** Returns */
            returns: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TagComparison
         * @description A per-tag activity comparison row.
         */
        TagComparison: {
            /** Cycled */
            cycled: number;
            /** Hours */
            hours: number;
            /** Kills */
            kills: number;
            /** Lootrate */
            lootRate: number;
            /** Pesper100Ped */
            pesPer100Ped: number;
            /** Sessions */
            sessions: number;
            /** Tagname */
            tagName: string;
        } & {
            [key: string]: unknown;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Codexpes */
            codexPes: number;
            /** Date */
            date: string;
            /** Ledgergains */
            ledgerGains: {
                [key: string]: unknown;
            };
            /** Ledgerlosses */
            ledgerLosses: {
                [key: string]: unknown;
            };
            /** Loottt */
            lootTt: number;
            /** Pes */
            pes: number;
            /** Questpes */
            questPes: number;
            /** Trackingcost */
            trackingCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolStat
         * @description A per-weapon stat row within a session detail.
         */
        ToolStat: {
            /** Costattributed */
            costAttributed: number;
            /** Crits */
            crits: number;
            /** Damagedealt */
            damageDealt: number;
            /** Shotsfired */
            shotsFired: number;
            /** Weaponname */
            weaponName: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingCostBreakdown
         * @description The cost breakdown within a session summary.
         */
        TrackingCostBreakdown: {
            /** Armourcost */
            armourCost: number;
            /** Enhancercost */
            enhancerCost: number;
            /** Healcost */
            healCost: number;
            /** Weaponcost */
            weaponCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingSession
         * @description A tracking-session summary row (history list).
         */
        TrackingSession: {
            /** Cost */
            cost: number;
            /** Duration */
            duration: number;
            /** Endtime */
            endTime?: string | null;
            /** Globals */
            globals: number;
            /** Hofs */
            hofs: number;
            /** Id */
            id: string;
            /** Net */
            net: number;
            /** Primarymobs */
            primaryMobs: string[];
            /** Primaryweapons */
            primaryWeapons: string[];
            /** Returnrate */
            returnRate: number;
            /** Returns */
            returns: number;
            /** Starttime */
            startTime?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingSnapshot
         * @description The consolidated dashboard hydration shape.
         *
         *     The union of the status, live, and recent-events readouts in one response:
         *     a newly mounted dashboard hydrates from this once, then reacts to pushed
         *     events rather than re-polling. Casing is preserved from the readouts it
         *     unions: ``session_id`` / ``started_at`` / ``kill_count`` stay snake-case,
         *     the headline numbers stay camelCase. Polymorphic across the three states;
         *     served with ``response_model_exclude_unset=True`` so each state keeps its
         *     own shape.
         */
        TrackingSnapshot: {
            /** Cost */
            cost?: number | null;
            /** Criticalhitstotal */
            criticalHitsTotal?: number | null;
            /** Cumulativenethistory */
            cumulativeNetHistory?: number[] | null;
            /** Currentmob */
            currentMob?: string | null;
            /** Currenttool */
            currentTool?: string | null;
            /** Damagedealttotal */
            damageDealtTotal?: number | null;
            /** Elapsed */
            elapsed?: number | null;
            /** Endofsessionarmourreminderenabled */
            endOfSessionArmourReminderEnabled?: boolean | null;
            /** Globalscount */
            globalsCount?: number | null;
            /** Hofscount */
            hofsCount?: number | null;
            /** Hotbarlisteneractive */
            hotbarListenerActive?: boolean | null;
            /** Kill Count */
            kill_count?: number | null;
            /** Latestkillloot */
            latestKillLoot?: number | null;
            /** Maxdamage */
            maxDamage?: number | null;
            /** Mobentrymode */
            mobEntryMode?: string | null;
            /** Mobsource */
            mobSource?: string | null;
            /** Multiplieravg */
            multiplierAvg?: number | null;
            /** Multiplierhistory */
            multiplierHistory?: number[] | null;
            /** Multiplierlast */
            multiplierLast?: number | null;
            /** Multipliermax */
            multiplierMax?: number | null;
            /** Net */
            net?: number | null;
            /** Pes */
            pes?: number | null;
            /** Recentevents */
            recentEvents?: components["schemas"]["NotableEvent"][] | null;
            /** Repairocrenabled */
            repairOcrEnabled?: boolean | null;
            /** Returnrate */
            returnRate?: number | null;
            /** Returns */
            returns?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Shotsfiredtotal */
            shotsFiredTotal?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Trifectaattribution */
            trifectaAttribution?: {
                [key: string]: unknown;
            } | null;
            /** Warnings */
            warnings?: components["schemas"]["NotableEvent"][] | null;
            /** Weaponattribution */
            weaponAttribution?: string | null;
            /** Weaponcost */
            weaponCost?: number | null;
            /** Weapondamagedealt */
            weaponDamageDealt?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeaponComparison
         * @description A per-weapon activity comparison row.
         */
        WeaponComparison: {
            /** Cycled */
            cycled: number;
            /** Hours */
            hours: number;
            /** Kills */
            kills: number;
            /** Lootrate */
            lootRate: number;
            /** Pesper100Ped */
            pesPer100Ped: number;
            /** Sessions */
            sessions: number;
            /** Weaponname */
            weaponName: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    demo_analytics_activity_api_demo_analytics_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsActivity"];
                };
            };
        };
    };
    demo_list_inventory_items_api_demo_analytics_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemModel"][];
                };
            };
        };
    };
    demo_list_ledger_api_demo_analytics_ledger_get: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from a prior page's X-Next-Cursor header; omit for the first page. */
                cursor?: string | null;
                /** @description Maximum entries per page (default 50, capped at 200). */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Cursor for the next page; absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerItem"][];
                };
            };
        };
    };
    demo_list_ledger_presets_api_demo_analytics_ledger_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPresetItem"][];
                };
            };
        };
    };
    demo_analytics_overview_api_demo_analytics_overview_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_get_session_api_demo_tracking_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_list_sessions_api_demo_tracking_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSession"][];
                };
            };
        };
    };
    demo_tracking_snapshot_api_demo_tracking_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSnapshot"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    delete_session_api_tracking_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeletedResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
