/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/demo/analytics/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Analytics Activity */
        get: operations["demo_analytics_activity_api_demo_analytics_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Inventory Items */
        get: operations["demo_list_inventory_items_api_demo_analytics_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Ledger */
        get: operations["demo_list_ledger_api_demo_analytics_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/ledger/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Ledger Presets */
        get: operations["demo_list_ledger_presets_api_demo_analytics_ledger_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Analytics Overview */
        get: operations["demo_analytics_overview_api_demo_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/tracking/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Get Session */
        get: operations["demo_get_session_api_demo_tracking_session__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/tracking/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo List Sessions */
        get: operations["demo_list_sessions_api_demo_tracking_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/tracking/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Tracking Snapshot */
        get: operations["demo_tracking_snapshot_api_demo_tracking_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/manual-mob-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Mob Lock
         * @description Immediately lock the selected catalogue mob for manual kill stamping.
         */
        post: operations["manual_mob_lock_api_tracking_manual_mob_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/manual-mob-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manual Mob Suggestions
         * @description Autocomplete suggestions for manual mob lock.
         */
        get: operations["manual_mob_suggestions_api_tracking_manual_mob_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/release-mob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release Mob
         * @description Release the currently locked mob.
         */
        post: operations["release_mob_api_tracking_release_mob_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get full session detail with aggregated summary.
         *
         *     Returns shape matching the frontend SessionDetail type.
         */
        get: operations["get_session_api_tracking_session__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a tracking session and all associated data.
         */
        delete: operations["delete_session_api_tracking_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/armour-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Armour Cost
         * @description Save armour repair cost to a session.
         */
        post: operations["set_armour_cost_api_tracking_session__session_id__armour_cost_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/loot-item/{item_name}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Activate Loot Item
         * @description Bulk-activate every previously-deactivated `kill_loot_items`
         *     row matching `item_name` in this session. Inverse of
         *     bulk_deactivate.
         */
        post: operations["bulk_activate_loot_item_api_tracking_session__session_id__loot_item__item_name__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/loot-item/{item_name}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Deactivate Loot Item
         * @description Bulk-deactivate every `kill_loot_items` row matching `item_name`
         *     in this session (item-name is URL-path encoded so spaces survive).
         *
         *     Atomically flips all active matching rows + rewrites each parent
         *     kill's `loot_total_ped` + invalidates `session_summaries`. 404 if
         *     the item isn't in this session at all; 409 if every matching row is
         *     already deactivated.
         */
        post: operations["bulk_deactivate_loot_item_api_tracking_session__session_id__loot_item__item_name__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/quest-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Session Quest Link
         * @description Persist the curated quest analytics linkage decision for a session.
         */
        post: operations["decide_session_quest_link_api_tracking_session__session_id__quest_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/quest-link-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Quest Link Suggestion
         * @description Get the curated post-session quest analytics linkage suggestion.
         */
        get: operations["get_session_quest_link_suggestion_api_tracking_session__session_id__quest_link_suggestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/rename-mob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename Session Mob
         * @description Rewrite kills.mob_name for matching kills in this session.
         *
         *     Atomically: preserves the pre-edit `mob_name` into
         *     `original_mob_name` via COALESCE (first-original semantics), rewrites
         *     `mob_name` for every matching kill in the session, invalidates the
         *     `session_summaries` cache row. 404 on missing session. 409 if the
         *     `fromMobName` value has no matching kills in the session, or if
         *     `fromMobName == toMobName` (the no-op rename would silently succeed
         *     otherwise).
         */
        post: operations["rename_session_mob_api_tracking_session__session_id__rename_mob_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/repair-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Repair Scan
         * @description Run OCR on the bundled-anchor repair region. Returns result without saving.
         */
        post: operations["repair_scan_api_tracking_session__session_id__repair_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}/restore-mob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Session Mob
         * @description Revert kills in this session whose current mob_name matches the
         *     request and carry a preserved `original_mob_name`.
         *
         *     Inverse of rename-mob. Atomically: rewrites `mob_name` back to
         *     `original_mob_name`, clears `original_mob_name`, invalidates the
         *     `session_summaries` cache. 404 on missing session. 409 if no kills
         *     in the session match the request (either nothing has been renamed
         *     to that current name, or no preserved original exists to restore).
         */
        post: operations["restore_session_mob_api_tracking_session__session_id__restore_mob_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List recent tracking sessions with aggregated stats.
         *
         *     Returns shapes matching the frontend TrackingSession type.
         */
        get: operations["list_sessions_api_tracking_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tracking Snapshot
         * @description Consolidated dashboard hydration: one response a newly mounted webview
         *     reads once, then keeps current from pushed events instead of re-polling.
         */
        get: operations["tracking_snapshot_api_tracking_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Tracking
         * @description Start a new tracking session.
         */
        post: operations["start_tracking_api_tracking_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Tracking
         * @description Stop the active tracking session.
         */
        post: operations["stop_tracking_api_tracking_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/tag-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tag Lock
         * @description Immediately set the active free-text tag for tag-mode kill stamping.
         */
        post: operations["tag_lock_api_tracking_tag_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/tag-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tag Suggestions
         * @description Autocomplete suggestions for free-text session mob tags.
         */
        get: operations["tag_suggestions_api_tracking_tag_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsActivity
         * @description The activity tab's mob / tag / weapon comparison tables.
         */
        AnalyticsActivity: {
            /** Mobcomparisons */
            mobComparisons: components["schemas"]["MobComparison"][];
            /** Tagcomparisons */
            tagComparisons: components["schemas"]["TagComparison"][];
            /** Weaponcomparisons */
            weaponComparisons: components["schemas"]["WeaponComparison"][];
        } & {
            [key: string]: unknown;
        };
        /** AnalyticsOverview */
        AnalyticsOverview: {
            lossesBreakdown: components["schemas"]["LossesBreakdown"];
            /** Monthlybreakdown */
            monthlyBreakdown: components["schemas"]["MonthlyPoint"][];
            returnsBreakdown: components["schemas"]["ReturnsBreakdown"];
            /** Timeline */
            timeline: components["schemas"]["TimelinePoint"][];
            /** Totalgains */
            totalGains: number;
            /** Totallosses */
            totalLosses: number;
            /** Totalreturnrate */
            totalReturnRate: number;
            /** Trend */
            trend: string;
        } & {
            [key: string]: unknown;
        };
        /** ArmourCostBody */
        ArmourCostBody: {
            /** Cost */
            cost: number;
        };
        /**
         * ArmourCostResult
         * @description Acknowledgement of a saved armour-repair cost.
         */
        ArmourCostResult: {
            /** Armourcost */
            armourCost: number;
            /** Sessionid */
            sessionId: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description The health-check acknowledgement.
         */
        HealthStatus: {
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InventoryItemModel
         * @description A persistent-inventory ledger item.
         */
        InventoryItemModel: {
            /** Acquiredat */
            acquiredAt: string;
            /** Id */
            id: string;
            /** Markuppaid */
            markupPaid: number;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Ttvalue */
            ttValue: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * LedgerItem
         * @description A liquid-economy ledger entry (expense or markup).
         */
        LedgerItem: {
            /** Amount */
            amount: number;
            /** Date */
            date: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Tag */
            tag: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * LedgerPresetItem
         * @description A ledger quick-entry preset (distinct from a ledger entry: name, not date).
         */
        LedgerPresetItem: {
            /** Amount */
            amount: number;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tag */
            tag: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * LootItem
         * @description An item-name aggregate loot row within a session detail.
         */
        LootItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Ttvalue */
            ttValue: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * LootItemEditResult
         * @description Acknowledgement of a bulk loot-item deactivate / activate.
         */
        LootItemEditResult: {
            /** Affectedrows */
            affectedRows: number;
            /** Itemname */
            itemName: string;
            /** Sessionid */
            sessionId: string;
            /** Sessiontotalreturns */
            sessionTotalReturns: number;
            /** Totalvaluedelta */
            totalValueDelta: number;
        } & {
            [key: string]: unknown;
        };
        /** LossesBreakdown */
        LossesBreakdown: {
            /** Cycledbreakdown */
            cycledBreakdown: unknown;
            /** Ledger */
            ledger: {
                [key: string]: number;
            };
            /** Trackingcost */
            trackingCost: number;
        } & {
            [key: string]: unknown;
        };
        /** ManualMobLockRequest */
        ManualMobLockRequest: {
            /**
             * Maturity
             * @default
             */
            maturity?: string;
            /** Species */
            species: string;
        };
        /**
         * ManualMobLockResult
         * @description Acknowledgement of a manual mob lock.
         */
        ManualMobLockResult: {
            /** Maturity */
            maturity: string;
            /** Mobname */
            mobName: string;
            /** Species */
            species: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ManualMobSuggestion
         * @description An autocomplete suggestion for manual mob lock.
         */
        ManualMobSuggestion: {
            /** Display */
            display: string;
            /** Maturity */
            maturity: string;
            /** Species */
            species: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * MobBreakdownRow
         * @description A per-mob row for the session metadata-edit affordance.
         */
        MobBreakdownRow: {
            /** Currentname */
            currentName: string;
            /** Killcount */
            killCount: number;
            /** Originalname */
            originalName?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MobComparison
         * @description A per-mob activity comparison row.
         */
        MobComparison: {
            /** Cycled */
            cycled: number;
            /** Hours */
            hours: number;
            /** Kills */
            kills: number;
            /** Lootrate */
            lootRate: number;
            /** Mobname */
            mobName: string;
            /** Pesper100Ped */
            pesPer100Ped: number;
            /** Sessions */
            sessions: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * MobEditResult
         * @description Acknowledgement of a session mob rename / restore.
         */
        MobEditResult: {
            /** Killcount */
            killCount: number;
            /** Mobname */
            mobName: string;
            /** Sessionid */
            sessionId: string;
        } & {
            [key: string]: unknown;
        };
        /** MonthlyPoint */
        MonthlyPoint: {
            /** Codexpes */
            codexPes: number;
            /** Ledgergains */
            ledgerGains: {
                [key: string]: unknown;
            };
            /** Ledgerlosses */
            ledgerLosses: {
                [key: string]: unknown;
            };
            /** Loottt */
            lootTt: number;
            /** Month */
            month: string;
            /** Pes */
            pes: number;
            /** Questpes */
            questPes: number;
            /** Trackingcost */
            trackingCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * NotableEvent
         * @description A dashboard activity-feed entry.
         *
         *     Covers both the notable-event payload (global/HoF/quest) and the tracker
         *     warning entry, which share ``type``/``description``/``value`` and differ in
         *     the optional ``eventType``/``timestamp``/``id`` keys.
         */
        NotableEvent: {
            /** Description */
            description: string;
            /** Eventtype */
            eventType?: string | null;
            /** Id */
            id?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Type */
            type: string;
            /** Value */
            value: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * QuestLinkDecisionResult
         * @description The accept/decline outcome of a quest-link decision.
         *
         *     Served with ``response_model_exclude_unset=True``: accept carries the link
         *     fields, decline carries only sessionId/status.
         */
        QuestLinkDecisionResult: {
            /** Linktype */
            linkType?: string | null;
            /** Playlistid */
            playlistId?: string | null;
            /** Playlistname */
            playlistName?: string | null;
            /** Questid */
            questId?: string | null;
            /** Questname */
            questName?: string | null;
            /** Sessionid */
            sessionId: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * QuestLinkSuggestion
         * @description The curated post-session quest-link suggestion (link fields nullable).
         */
        QuestLinkSuggestion: {
            /** Playlistid */
            playlistId?: string | null;
            /** Playlistname */
            playlistName?: string | null;
            /** Questid */
            questId?: string | null;
            /** Questname */
            questName?: string | null;
            /** Reason */
            reason: string;
            /** Sessionid */
            sessionId: string;
            /** Suggestiontype */
            suggestionType: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ReleaseMobResult
         * @description The released mob/tag label, or null if nothing was locked.
         */
        ReleaseMobResult: {
            /** Released */
            released?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RenameMobRequest */
        RenameMobRequest: {
            /** Frommobname */
            fromMobName: string;
            /** Tomobname */
            toMobName: string;
        };
        /**
         * RepairScanResult
         * @description A repair-cost OCR scan result.
         *
         *     The ``error`` key is intentionally undeclared: the failure branch adds it and
         *     ``extra="allow"`` passes it through, so the success branch never gains a null
         *     error key.
         */
        RepairScanResult: {
            /** Confidence */
            confidence: number;
            /** Cost Ped */
            cost_ped: number;
            /** Raw Text */
            raw_text: string;
        } & {
            [key: string]: unknown;
        };
        /** RestoreMobRequest */
        RestoreMobRequest: {
            /** Currentmobname */
            currentMobName: string;
        };
        /** ReturnsBreakdown */
        ReturnsBreakdown: {
            /** Codexpes */
            codexPes: number;
            /** Ledger */
            ledger: {
                [key: string]: number;
            };
            /** Loottt */
            lootTt: number;
            /** Pes */
            pes: number;
            /** Questpes */
            questPes: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionDeletedResult
         * @description Acknowledgement that a session was deleted (2-key).
         */
        SessionDeletedResult: {
            /** Sessionid */
            sessionId: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionDetail
         * @description The expanded detail for a session.
         */
        SessionDetail: {
            /** Deactivatedlootbreakdown */
            deactivatedLootBreakdown: components["schemas"]["LootItem"][];
            /** Effectiveloot */
            effectiveLoot: number;
            /** Lootbreakdown */
            lootBreakdown: components["schemas"]["LootItem"][];
            /** Mobbreakdown */
            mobBreakdown: components["schemas"]["MobBreakdownRow"][];
            /** Mobentrymode */
            mobEntryMode: string;
            /** Notableevents */
            notableEvents: components["schemas"]["SessionNotableEvent"][];
            /** Sessionid */
            sessionId: string;
            /** Skillgains */
            skillGains: components["schemas"]["SessionSkillGain"][];
            summary: components["schemas"]["SessionSummary"];
            /** Toolstats */
            toolStats: components["schemas"]["ToolStat"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionNotableEvent
         * @description A notable event within a session detail (target/item shape).
         */
        SessionNotableEvent: {
            /** Eventtype */
            eventType: string;
            /** Item */
            item: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Value */
            value: number;
        } & {
            [key: string]: unknown;
        };
        /** SessionQuestLinkDecisionBody */
        SessionQuestLinkDecisionBody: {
            /** Action */
            action: string;
        };
        /**
         * SessionSkillGain
         * @description A per-skill gain within a session detail.
         */
        SessionSkillGain: {
            /** Level */
            level: number;
            /** Skillname */
            skillName: string;
            /** Ttvaluegained */
            ttValueGained: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionSummary
         * @description The headline summary of a session detail.
         */
        SessionSummary: {
            /** Cost */
            cost: number;
            costBreakdown: components["schemas"]["TrackingCostBreakdown"];
            /** Duration */
            duration: number;
            /** Kills */
            kills: number;
            /** Net */
            net: number;
            /** Pes */
            pes: number;
            /** Returnrate */
            returnRate: number;
            /** Returns */
            returns: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TagComparison
         * @description A per-tag activity comparison row.
         */
        TagComparison: {
            /** Cycled */
            cycled: number;
            /** Hours */
            hours: number;
            /** Kills */
            kills: number;
            /** Lootrate */
            lootRate: number;
            /** Pesper100Ped */
            pesPer100Ped: number;
            /** Sessions */
            sessions: number;
            /** Tagname */
            tagName: string;
        } & {
            [key: string]: unknown;
        };
        /** TagLockRequest */
        TagLockRequest: {
            /** Tag */
            tag: string;
        };
        /**
         * TagLockResult
         * @description Acknowledgement of a free-text tag lock.
         */
        TagLockResult: {
            /** Tag */
            tag: string;
        } & {
            [key: string]: unknown;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Codexpes */
            codexPes: number;
            /** Date */
            date: string;
            /** Ledgergains */
            ledgerGains: {
                [key: string]: unknown;
            };
            /** Ledgerlosses */
            ledgerLosses: {
                [key: string]: unknown;
            };
            /** Loottt */
            lootTt: number;
            /** Pes */
            pes: number;
            /** Questpes */
            questPes: number;
            /** Trackingcost */
            trackingCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolStat
         * @description A per-weapon stat row within a session detail.
         */
        ToolStat: {
            /** Costattributed */
            costAttributed: number;
            /** Crits */
            crits: number;
            /** Damagedealt */
            damageDealt: number;
            /** Shotsfired */
            shotsFired: number;
            /** Weaponname */
            weaponName: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingCostBreakdown
         * @description The cost breakdown within a session summary.
         */
        TrackingCostBreakdown: {
            /** Armourcost */
            armourCost: number;
            /** Enhancercost */
            enhancerCost: number;
            /** Healcost */
            healCost: number;
            /** Weaponcost */
            weaponCost: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingSession
         * @description A tracking-session summary row (history list).
         */
        TrackingSession: {
            /** Cost */
            cost: number;
            /** Duration */
            duration: number;
            /** Endtime */
            endTime?: string | null;
            /** Globals */
            globals: number;
            /** Hofs */
            hofs: number;
            /** Id */
            id: string;
            /** Net */
            net: number;
            /** Primarymobs */
            primaryMobs: string[];
            /** Primaryweapons */
            primaryWeapons: string[];
            /** Returnrate */
            returnRate: number;
            /** Returns */
            returns: number;
            /** Starttime */
            startTime?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingSnapshot
         * @description The consolidated dashboard hydration shape.
         *
         *     The union of the status, live, and recent-events readouts in one response:
         *     a newly mounted dashboard hydrates from this once, then reacts to pushed
         *     events rather than re-polling. Casing is preserved from the readouts it
         *     unions: ``session_id`` / ``started_at`` / ``kill_count`` stay snake-case,
         *     the headline numbers stay camelCase. Polymorphic across the three states;
         *     served with ``response_model_exclude_unset=True`` so each state keeps its
         *     own shape.
         */
        TrackingSnapshot: {
            /** Cost */
            cost?: number | null;
            /** Criticalhitstotal */
            criticalHitsTotal?: number | null;
            /** Cumulativenethistory */
            cumulativeNetHistory?: number[] | null;
            /** Currentmob */
            currentMob?: string | null;
            /** Currenttool */
            currentTool?: string | null;
            /** Damagedealttotal */
            damageDealtTotal?: number | null;
            /** Elapsed */
            elapsed?: number | null;
            /** Endofsessionarmourreminderenabled */
            endOfSessionArmourReminderEnabled?: boolean | null;
            /** Globalscount */
            globalsCount?: number | null;
            /** Hofscount */
            hofsCount?: number | null;
            /** Hotbarlisteneractive */
            hotbarListenerActive?: boolean | null;
            /** Kill Count */
            kill_count?: number | null;
            /** Latestkillloot */
            latestKillLoot?: number | null;
            /** Maxdamage */
            maxDamage?: number | null;
            /** Mobentrymode */
            mobEntryMode?: string | null;
            /** Mobsource */
            mobSource?: string | null;
            /** Multiplieravg */
            multiplierAvg?: number | null;
            /** Multiplierhistory */
            multiplierHistory?: number[] | null;
            /** Multiplierlast */
            multiplierLast?: number | null;
            /** Multipliermax */
            multiplierMax?: number | null;
            /** Net */
            net?: number | null;
            /** Pes */
            pes?: number | null;
            /** Recentevents */
            recentEvents?: components["schemas"]["NotableEvent"][] | null;
            /** Repairocrenabled */
            repairOcrEnabled?: boolean | null;
            /** Returnrate */
            returnRate?: number | null;
            /** Returns */
            returns?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Shotsfiredtotal */
            shotsFiredTotal?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Trifectaattribution */
            trifectaAttribution?: {
                [key: string]: unknown;
            } | null;
            /** Warnings */
            warnings?: components["schemas"]["NotableEvent"][] | null;
            /** Weaponattribution */
            weaponAttribution?: string | null;
            /** Weaponcost */
            weaponCost?: number | null;
            /** Weapondamagedealt */
            weaponDamageDealt?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingStartResult
         * @description Acknowledgement that a tracking session started.
         */
        TrackingStartResult: {
            /** Session Id */
            session_id: string;
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingStopResult
         * @description Acknowledgement that the active tracking session stopped.
         */
        TrackingStopResult: {
            /** Ended At */
            ended_at?: string | null;
            /** Kill Count */
            kill_count: number;
            /** Session Id */
            session_id: string;
            /** Started At */
            started_at: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeaponComparison
         * @description A per-weapon activity comparison row.
         */
        WeaponComparison: {
            /** Cycled */
            cycled: number;
            /** Hours */
            hours: number;
            /** Kills */
            kills: number;
            /** Lootrate */
            lootRate: number;
            /** Pesper100Ped */
            pesPer100Ped: number;
            /** Sessions */
            sessions: number;
            /** Weaponname */
            weaponName: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    demo_analytics_activity_api_demo_analytics_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsActivity"];
                };
            };
        };
    };
    demo_list_inventory_items_api_demo_analytics_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemModel"][];
                };
            };
        };
    };
    demo_list_ledger_api_demo_analytics_ledger_get: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from a prior page's X-Next-Cursor header; omit for the first page. */
                cursor?: string | null;
                /** @description Maximum entries per page (default 50, capped at 200). */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Cursor for the next page; absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerItem"][];
                };
            };
        };
    };
    demo_list_ledger_presets_api_demo_analytics_ledger_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPresetItem"][];
                };
            };
        };
    };
    demo_analytics_overview_api_demo_analytics_overview_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_get_session_api_demo_tracking_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_list_sessions_api_demo_tracking_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSession"][];
                };
            };
        };
    };
    demo_tracking_snapshot_api_demo_tracking_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSnapshot"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    manual_mob_lock_api_tracking_manual_mob_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualMobLockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualMobLockResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_mob_suggestions_api_tracking_manual_mob_suggestions_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualMobSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_mob_api_tracking_release_mob_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseMobResult"];
                };
            };
        };
    };
    get_session_api_tracking_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_tracking_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeletedResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_armour_cost_api_tracking_session__session_id__armour_cost_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArmourCostBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArmourCostResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_activate_loot_item_api_tracking_session__session_id__loot_item__item_name__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                item_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LootItemEditResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_deactivate_loot_item_api_tracking_session__session_id__loot_item__item_name__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                item_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LootItemEditResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_session_quest_link_api_tracking_session__session_id__quest_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionQuestLinkDecisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestLinkDecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_quest_link_suggestion_api_tracking_session__session_id__quest_link_suggestion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestLinkSuggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_mob_api_tracking_session__session_id__rename_mob_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameMobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobEditResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_scan_api_tracking_session__session_id__repair_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepairScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_session_mob_api_tracking_session__session_id__restore_mob_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreMobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobEditResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_tracking_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSession"][];
                };
            };
        };
    };
    tracking_snapshot_api_tracking_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSnapshot"];
                };
            };
        };
    };
    start_tracking_api_tracking_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingStartResult"];
                };
            };
        };
    };
    stop_tracking_api_tracking_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingStopResult"];
                };
            };
        };
    };
    tag_lock_api_tracking_tag_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagLockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagLockResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tag_suggestions_api_tracking_tag_suggestions_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
