/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracking/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a tracking session and all associated data.
         */
        delete: operations["delete_session_api_tracking_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description The health-check acknowledgement.
         */
        HealthStatus: {
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * NotableEvent
         * @description A dashboard activity-feed entry.
         *
         *     Covers both the notable-event payload (global/HoF/quest) and the tracker
         *     warning entry, which share ``type``/``description``/``value`` and differ in
         *     the optional ``eventType``/``timestamp``/``id`` keys.
         */
        NotableEvent: {
            /** Description */
            description: string;
            /** Eventtype */
            eventType?: string | null;
            /** Id */
            id?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Type */
            type: string;
            /** Value */
            value: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionDeletedResult
         * @description Acknowledgement that a session was deleted (2-key).
         */
        SessionDeletedResult: {
            /** Sessionid */
            sessionId: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * TrackingSnapshot
         * @description The consolidated dashboard hydration shape.
         *
         *     The union of the status, live, and recent-events readouts in one response:
         *     a newly mounted dashboard hydrates from this once, then reacts to pushed
         *     events rather than re-polling. Casing is preserved from the readouts it
         *     unions: ``session_id`` / ``started_at`` / ``kill_count`` stay snake-case,
         *     the headline numbers stay camelCase. Polymorphic across the three states;
         *     served with ``response_model_exclude_unset=True`` so each state keeps its
         *     own shape.
         */
        TrackingSnapshot: {
            /** Cost */
            cost?: number | null;
            /** Criticalhitstotal */
            criticalHitsTotal?: number | null;
            /** Cumulativenethistory */
            cumulativeNetHistory?: number[] | null;
            /** Currentmob */
            currentMob?: string | null;
            /** Currenttool */
            currentTool?: string | null;
            /** Damagedealttotal */
            damageDealtTotal?: number | null;
            /** Elapsed */
            elapsed?: number | null;
            /** Endofsessionarmourreminderenabled */
            endOfSessionArmourReminderEnabled?: boolean | null;
            /** Globalscount */
            globalsCount?: number | null;
            /** Hofscount */
            hofsCount?: number | null;
            /** Hotbarlisteneractive */
            hotbarListenerActive?: boolean | null;
            /** Kill Count */
            kill_count?: number | null;
            /** Latestkillloot */
            latestKillLoot?: number | null;
            /** Maxdamage */
            maxDamage?: number | null;
            /** Mobentrymode */
            mobEntryMode?: string | null;
            /** Mobsource */
            mobSource?: string | null;
            /** Multiplieravg */
            multiplierAvg?: number | null;
            /** Multiplierhistory */
            multiplierHistory?: number[] | null;
            /** Multiplierlast */
            multiplierLast?: number | null;
            /** Multipliermax */
            multiplierMax?: number | null;
            /** Net */
            net?: number | null;
            /** Pes */
            pes?: number | null;
            /** Recentevents */
            recentEvents?: components["schemas"]["NotableEvent"][] | null;
            /** Repairocrenabled */
            repairOcrEnabled?: boolean | null;
            /** Returnrate */
            returnRate?: number | null;
            /** Returns */
            returns?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Shotsfiredtotal */
            shotsFiredTotal?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Trifectaattribution */
            trifectaAttribution?: {
                [key: string]: unknown;
            } | null;
            /** Warnings */
            warnings?: components["schemas"]["NotableEvent"][] | null;
            /** Weaponattribution */
            weaponAttribution?: string | null;
            /** Weaponcost */
            weaponCost?: number | null;
            /** Weapondamagedealt */
            weaponDamageDealt?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    delete_session_api_tracking_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeletedResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
