/**
 * Analytics- and character-surface types. The wire shapes re-export
 * from the generated bindings (the authoritative contract); the
 * handful of renamed exports alias the generated types the consumers
 * adopted under other names.
 */

export type {
	AnalyticsOverview as OverviewStats,
	CalibrationStatus,
	CharacterProspectOptions,
	CodexClaimResult,
	CodexMasteryClaimResult,
	CodexMetaAttribute,
	CodexMetaClaimResult,
	CodexRank as CodexRankItem,
	CodexSkillOption,
	CodexSpecies,
	CodexSpeciesRanks as CodexRankBreakdown,
	ComputedCharacterStats,
	CycledBreakdown,
	ExcludedSkill,
	HpOptimizerAttribute,
	HpOptimizerResult,
	HpOptimizerSkill,
	InventoryItem,
	InventorySellResult,
	LedgerItem as LedgerEntry,
	LedgerKind as LedgerEntryType,
	LedgerPreset,
	LossesBreakdown,
	MobComparison,
	MonthlyEntry,
	OptimizerAttribute,
	OptimizerSkill,
	PathAllocation,
	PathOptimizerResult,
	ProfessionLevel,
	ProfessionOptimizerResult,
	ProspectOption,
	ProspectResult,
	ProspectRow,
	ProspectSample,
	ProspectSliceType,
	ReturnsBreakdown,
	SkillLevel,
	StatProfession,
	TagComparison,
	TimelineDay,
	WeaponComparison,
} from '$lib/api/commands.gen';
